# F_S3 — Shape Classification on New Parameterized Data

Implements the full **global-to-shape decision hierarchy**:

1. **Gate 1** — MIC → global relationship strength (strong / intermediate / none)
2. **Gate 2** — |Pearson| & |Spearman| → Simple vs Complex
3. **Simple path, power gate** — power-law fit → Linear / Concave / Convex / next cubic–S–Threshold gate
4. **Complex path** — Branching / Threshold / Turning-point → subtypes

Reads from `F/output/S1_parameterized/` and `F/output/S2_parameterized/`.

In [1]:
from __future__ import annotations

import json
import math
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit

try:
    from tqdm.auto import tqdm
except ImportError:
    def tqdm(it, **kw):
        return it

warnings.filterwarnings('ignore')

def count_percent(count, total):
    count = int(count)
    total = int(total)
    return f'{count:,} ({count / total:.1%})' if total else f'{count:,} (N/A)'

def locate_repo_root() -> Path:
    for root in [Path.cwd().resolve(), *Path.cwd().resolve().parents]:
        if (root / 'D').is_dir() and (root / 'E').is_dir():
            return root
    raise FileNotFoundError('Could not locate repo root.')

REPO_ROOT = locate_repo_root()
S1_DIR = REPO_ROOT / 'F' / 'output' / 'S1_parameterized'
S2_DIR = REPO_ROOT / 'F' / 'output' / 'S2_metrics'
OUT_DIR = REPO_ROOT / 'F' / 'output' / 'S3_shape_classification_new_data'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Gate 1 thresholds ──
MIC_STRONG = 0.8
MIC_INTERMEDIATE = 0.6

# ── Gate 2 thresholds ──
SIMPLE_CORR_THRESHOLD = 0.7

# ── Simple path thresholds ──
R2_POWER_THRESHOLD = 0.90          # min R² for adequate power-law fit
LINEAR_B_TOLERANCE = 0.05          # |b - 1| <= this → Linear
S_SHAPE_SHARPNESS_MAX = 6.0        # max deriv / median deriv below this → S-shaped (not threshold)
THRESHOLD_SHARPNESS_MIN = 6.0      # max deriv / median deriv above this → Threshold

# ── Complex path thresholds ──
BRANCHING_GAP_RATIO = 0.25         # gap / y_range in a bin to count as branching evidence
BRANCHING_MIN_BINS = 3             # min bins showing gaps
COMPLEX_THRESHOLD_DERIV_RATIO = 5.0  # derivative spike ratio for threshold detection

print(f'Gate 1: strong MIC >= {MIC_STRONG}, intermediate MIC >= {MIC_INTERMEDIATE}')
print(f'Gate 2: Simple when |r| >= {SIMPLE_CORR_THRESHOLD} AND |ρ| >= {SIMPLE_CORR_THRESHOLD}')
print(f'Simple path: power-law R² >= {R2_POWER_THRESHOLD}, linear |b−1| <= {LINEAR_B_TOLERANCE}')
print(f'Complex path: branching gap ratio >= {BRANCHING_GAP_RATIO} in >= {BRANCHING_MIN_BINS} bins')

Gate 1: strong MIC >= 0.8, intermediate MIC >= 0.6
Gate 2: Simple when |r| >= 0.7 AND |ρ| >= 0.7
Simple path: power-law R² >= 0.9, linear |b−1| <= 0.05
Complex path: branching gap ratio >= 0.25 in >= 3 bins

/Users/mimi/miniconda3/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Family catalogue

Ground-truth properties for each signal family, used for validation at the end.

In [2]:
# Family catalogue: ground-truth properties for each signal family.
# F17 (Quadratic peak) was removed in F; F18 is standalone.
FAMILY_CATALOGUE = {
    'F01': {'name': 'Linear positive',           'direction': 'positive',     'linearity': 'linear',              'monotonicity': 'monotonic',     'curvature': 'N/A',    'special_shape': 'none',                  'tp': 0},
    'F02': {'name': 'Linear negative',           'direction': 'negative',     'linearity': 'linear',              'monotonicity': 'monotonic',     'curvature': 'N/A',    'special_shape': 'none',                  'tp': 0},
    'F03': {'name': 'Power convex positive',     'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'convex', 'special_shape': 'none',                  'tp': 0},
    'F04': {'name': 'Power convex negative',     'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'concave','special_shape': 'none',                  'tp': 0},
    'F05': {'name': 'Power concave positive',    'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'concave','special_shape': 'none',                  'tp': 0},
    'F06': {'name': 'Power concave negative',    'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'convex', 'special_shape': 'none',                  'tp': 0},
    'F07': {'name': 'Saturation positive',       'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'concave','special_shape': 'saturation',            'tp': 0},
    'F08': {'name': 'Saturation negative',       'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'convex', 'special_shape': 'saturation',            'tp': 0},
    'F09': {'name': 'Log positive',              'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'concave','special_shape': 'none',                  'tp': 0},
    'F10': {'name': 'Log negative',              'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'convex', 'special_shape': 'none',                  'tp': 0},
    'F11': {'name': 'Exponential positive',      'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'convex', 'special_shape': 'none',                  'tp': 0},
    'F12': {'name': 'Exponential negative',      'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'concave','special_shape': 'none',                  'tp': 0},
    'F13': {'name': 'S-curve positive',          'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'mixed',  'special_shape': 'S-curve',               'tp': 0},
    'F14': {'name': 'S-curve negative',          'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'mixed',  'special_shape': 'S-curve',               'tp': 0},
    'F15': {'name': 'Threshold positive',        'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'N/A',    'special_shape': 'threshold',             'tp': 0},
    'F16': {'name': 'Threshold negative',        'direction': 'negative',     'linearity': 'nonlinear',           'monotonicity': 'monotonic',     'curvature': 'N/A',    'special_shape': 'threshold',             'tp': 0},
    'F18': {'name': 'Quadratic valley (U)',       'direction': 'none/local',   'linearity': 'nonlinear',           'monotonicity': 'non-monotonic', 'curvature': 'convex', 'special_shape': 'valley',                'tp': 1},
    'F19': {'name': 'Spike',                     'direction': 'none/local',   'linearity': 'nonlinear',           'monotonicity': 'non-monotonic', 'curvature': 'N/A',    'special_shape': 'spike',                 'tp': 1},
    'F20': {'name': 'Inverted Spike',            'direction': 'none/local',   'linearity': 'nonlinear',           'monotonicity': 'non-monotonic', 'curvature': 'N/A',    'special_shape': 'inverted spike',        'tp': 1},
    'F21': {'name': 'Cubic',                     'direction': 'none/mixed',   'linearity': 'nonlinear',           'monotonicity': 'non-monotonic', 'curvature': 'mixed',  'special_shape': 'cubic',                 'tp': 2},
    'F22': {'name': 'Oscillation',               'direction': 'none/mixed',   'linearity': 'nonlinear',           'monotonicity': 'non-monotonic', 'curvature': 'mixed',  'special_shape': 'oscillation',           'tp': 'multiple'},
    'F23': {'name': 'Two Lines',                 'direction': 'positive',     'linearity': 'multi-branch linear', 'monotonicity': 'multi-branch',  'curvature': 'N/A',    'special_shape': 'two lines',             'tp': 0},
    'F24': {'name': 'Line and Parabola',         'direction': 'none/local',   'linearity': 'multi-branch',        'monotonicity': 'multi-branch',  'curvature': 'mixed',  'special_shape': 'line + parabola',       'tp': 1},
    'F25': {'name': 'Multi-regime threshold',    'direction': 'positive',     'linearity': 'multi-branch',        'monotonicity': 'multi-branch',  'curvature': 'convex', 'special_shape': 'overlapping J',         'tp': 'multiple'},
    'F26': {'name': 'Windowed threshold',        'direction': 'positive',     'linearity': 'nonlinear',           'monotonicity': 'non-monotonic', 'curvature': 'convex', 'special_shape': 'windowed J',            'tp': 'multiple'},
    'Null': {'name': 'No relationship',          'direction': 'N/A',          'linearity': 'N/A',                 'monotonicity': 'N/A',           'curvature': 'N/A',    'special_shape': 'none',                  'tp': 'N/A'},
}

# Build the expected shape_label mapping from the catalogue.
# This is the ground-truth: what shape should the classifier assign at high SNR?
EXPECTED_SHAPE = {}
for fid, props in FAMILY_CATALOGUE.items():
    if fid == 'Null':
        EXPECTED_SHAPE[fid] = 'no_global'
        continue
    d = props['direction']
    mono = props['monotonicity']
    lin = props['linearity']
    curv = props['curvature']
    shape = props['special_shape']
    tp = props['tp']

    # Simple monotonic families → gate2 = Simple
    if mono == 'monotonic':
        if lin == 'linear':
            EXPECTED_SHAPE[fid] = f'{d}_line'
        elif shape == 'S-curve':
            EXPECTED_SHAPE[fid] = f'{d}_s_shaped'
        elif shape == 'threshold':
            EXPECTED_SHAPE[fid] = f'{d}_threshold'
        elif curv == 'concave':
            EXPECTED_SHAPE[fid] = f'{d}_concave'
        elif curv == 'convex':
            EXPECTED_SHAPE[fid] = f'{d}_convex'
        else:
            EXPECTED_SHAPE[fid] = 'simple_other'
    # Non-monotonic / multi-branch → gate2 = Complex
    elif mono == 'non-monotonic':
        if tp == 1:
            EXPECTED_SHAPE[fid] = 'u_inv_u_spike'
        elif tp == 2:
            EXPECTED_SHAPE[fid] = 'complex_cubic'
        elif tp == 'multiple' and 'oscillat' in shape:
            EXPECTED_SHAPE[fid] = 'oscillatory'
        elif tp == 'multiple' and 'windowed' in shape:
            EXPECTED_SHAPE[fid] = 'multi_step_threshold'
        else:
            EXPECTED_SHAPE[fid] = 'complex_uncertain'
    elif mono == 'multi-branch':
        if 'two lines' in shape:
            EXPECTED_SHAPE[fid] = '2_way_branching'
        elif 'parabola' in shape:
            EXPECTED_SHAPE[fid] = '2_way_branching'
        elif 'overlapping' in shape or 'J' in shape:
            EXPECTED_SHAPE[fid] = 'n_way_branching'
        else:
            EXPECTED_SHAPE[fid] = 'complex_uncertain'

catalogue_df = pd.DataFrame.from_dict(FAMILY_CATALOGUE, orient='index').reset_index(names='family_id')
catalogue_df['expected_shape'] = catalogue_df['family_id'].map(EXPECTED_SHAPE)
print(f'{len(FAMILY_CATALOGUE)} families loaded')
display(catalogue_df[['family_id', 'name', 'monotonicity', 'curvature', 'special_shape', 'expected_shape']])

26 families loaded

,family_id,name,monotonicity,curvature,special_shape,expected_shape
0,F01,Linear positive,monotonic,N/A,none,positive_line
1,F02,Linear negative,monotonic,N/A,none,negative_line
2,F03,Power convex positive,monotonic,convex,none,positive_convex
3,F04,Power convex negative,monotonic,concave,none,negative_concave
4,F05,Power concave positive,monotonic,concave,none,positive_concave
5,F06,Power concave negative,monotonic,convex,none,negative_convex
6,F07,Saturation positive,monotonic,concave,saturation,positive_concave
7,F08,Saturation negative,monotonic,convex,saturation,negative_convex
8,F09,Log positive,monotonic,concave,none,positive_concave
9,F10,Log negative,monotonic,convex,none,negative_convex
10,F11,Exponential positive,monotonic,convex,none,positive_convex
11,F12,Exponential negative,monotonic,concave,none,negative_concave
12,F13,S-curve positive,monotonic,mixed,S-curve,positive_s_shaped
13,F14,S-curve negative,monotonic,mixed,S-curve,negative_s_shaped
14,F15,Threshold positive,monotonic,N/A,threshold,positive_threshold
15,F16,Threshold negative,monotonic,N/A,threshold,negative_threshold
16,F18,Quadratic valley (U),non-monotonic,convex,valley,u_inv_u_spike
17,F19,Spike,non-monotonic,N/A,spike,u_inv_u_spike
18,F20,Inverted Spike,non-monotonic,N/A,inverted spike,u_inv_u_spike
19,F21,Cubic,non-monotonic,mixed,cubic,complex_cubic
20,F22,Oscillation,non-monotonic,mixed,oscillation,oscillatory
21,F23,Two Lines,multi-branch,N/A,two lines,2_way_branching
22,F24,Line and Parabola,multi-branch,mixed,line + parabola,2_way_branching
23,F25,Multi-regime threshold,multi-branch,convex,overlapping J,n_way_branching
24,F26,Windowed threshold,non-monotonic,convex,windowed J,multi_step_threshold
25,Null,No relationship,N/A,N/A,none,no_global

## Load data

In [3]:
cases_df = pd.read_csv(S1_DIR / 'cases.csv', low_memory=False)
cases_df['_pt_idx'] = np.arange(len(cases_df), dtype=np.int64)
metrics_df = pd.read_parquet(S2_DIR / 'metrics_full.parquet')
pts = np.load(S1_DIR / 'scatter_points.npz')
x_all = pts['x']
y_all = pts['y']
del pts

if len(x_all) != len(cases_df) or len(y_all) != len(cases_df):
    raise ValueError('Scatter arrays and cases.csv must contain the same number of rows.')
if cases_df['case_id'].duplicated().any() or metrics_df['case_id'].duplicated().any():
    raise ValueError('case_id must be unique in both cases and metrics.')

data = cases_df.merge(metrics_df, on='case_id', how='inner', validate='one_to_one')
data = data.reset_index(drop=True)
data['is_null'] = data['family_id'].eq('Null')
data['_pt_idx'] = pd.to_numeric(data['_pt_idx'], errors='raise').astype(np.int64)
if not data['_pt_idx'].between(0, len(x_all) - 1).all():
    raise IndexError('A mapped scatter-point index is outside the stored arrays.')
if data['_pt_idx'].duplicated().any():
    raise ValueError('Multiple classified cases map to the same scatter-point row.')

print(f'Loaded {len(data):,} metric-covered cases × {x_all.shape[1]} points')
print(f'  Metrics coverage: {len(data):,} / {len(cases_df):,} ({len(data) / len(cases_df):.1%})')
print(f'  Signal: {(~data["is_null"]).sum():,}   Null: {data["is_null"].sum():,}')
print(f'  MIC range: [{data["MIC"].min():.3f}, {data["MIC"].max():.3f}]')

Loaded 335,960 metric-covered cases × 500 points
  Metrics coverage: 335,960 / 1,144,080 (29.4%)
  Signal: 326,880   Null: 9,080
  MIC range: [0.122, 1.000]

## Gate 1 — Global relationship (MIC)

- **Strong**: MIC ≥ 0.8 → proceed to Gate 2
- **Intermediate**: 0.6 ≤ MIC < 0.8 → classification stops here
- **No global**: MIC < 0.6 → no relationship detected

In [4]:
def assign_gate1(mic):
    if mic >= MIC_STRONG:
        return 'strong_global'
    elif mic >= MIC_INTERMEDIATE:
        return 'intermediate_global'
    else:
        return 'no_global'

data['gate1'] = data['MIC'].apply(assign_gate1)

_g1_counts = data.groupby(['family_id', 'gate1']).size().unstack(fill_value=0)
_g1_counts = _g1_counts.reindex(
    columns=['strong_global', 'intermediate_global', 'no_global'], fill_value=0
).sort_index()
_g1_totals = _g1_counts.sum(axis=1)
_g1 = pd.DataFrame(index=_g1_counts.index)
_g1['family_name'] = _g1.index.map(lambda f: FAMILY_CATALOGUE.get(f, {}).get('name', ''))
_g1['Total'] = [count_percent(n, n) for n in _g1_totals]
for col in _g1_counts.columns:
    _g1[col] = [count_percent(n, total) for n, total in zip(_g1_counts[col], _g1_totals)]
print('=== Gate 1: Per-family MIC classification ===')
display(_g1)
print(f'\nOverall: {count_percent((data["gate1"]=="strong_global").sum(), len(data))} strong / '
      f'{count_percent((data["gate1"]=="intermediate_global").sum(), len(data))} intermediate / '
      f'{count_percent((data["gate1"]=="no_global").sum(), len(data))} no_global')

=== Gate 1: Per-family MIC classification ===

,family_name,Total,strong_global,intermediate_global,no_global
family_id,,,,,
F01,Linear positive,"27,240 (100.0%)","11,756 (43.2%)","1,881 (6.9%)","13,603 (49.9%)"
F03,Power convex positive,"27,240 (100.0%)","10,576 (38.8%)","2,346 (8.6%)","14,318 (52.6%)"
F05,Power concave positive,"27,240 (100.0%)","11,057 (40.6%)","2,064 (7.6%)","14,119 (51.8%)"
F07,Saturation positive,"27,240 (100.0%)","2,936 (10.8%)","4,487 (16.5%)","19,817 (72.7%)"
F13,S-curve positive,"27,240 (100.0%)","11,933 (43.8%)","1,860 (6.8%)","13,447 (49.4%)"
F15,Threshold positive,"27,240 (100.0%)","12,566 (46.1%)","1,447 (5.3%)","13,227 (48.6%)"
F18,Quadratic valley (U),"27,240 (100.0%)","10,290 (37.8%)","2,527 (9.3%)","14,423 (52.9%)"
F21,Cubic,"27,240 (100.0%)","6,578 (24.1%)","4,335 (15.9%)","16,327 (59.9%)"
F22,Oscillation,"27,240 (100.0%)","11,997 (44.0%)","1,627 (6.0%)","13,616 (50.0%)"
F23,Two Lines,"27,240 (100.0%)","2,412 (8.9%)","5,237 (19.2%)","19,591 (71.9%)"
F25,Multi-regime threshold,"27,240 (100.0%)",190 (0.7%),"3,838 (14.1%)","23,212 (85.2%)"
F26,Windowed threshold,"27,240 (100.0%)",171 (0.6%),"1,057 (3.9%)","26,012 (95.5%)"
Null,No relationship,"9,080 (100.0%)",0 (0.0%),0 (0.0%),"9,080 (100.0%)"

Overall: 92,462 (27.5%) strong / 32,706 (9.7%) intermediate / 210,792 (62.7%) no_global

## Gate 2 — Simple or Complex

Applied only to **strong global** cases (MIC ≥ 0.8).

- **Simple**: |Pearson r| ≥ 0.7 AND |Spearman ρ| ≥ 0.7
- **Complex**: otherwise

In [5]:
mask_strong = data['gate1'] == 'strong_global'

data['gate2'] = None
data.loc[mask_strong, 'gate2'] = np.where(
    (data.loc[mask_strong, 'pearson_r'].abs() >= SIMPLE_CORR_THRESHOLD)
    & (data.loc[mask_strong, 'spearman_rho'].abs() >= SIMPLE_CORR_THRESHOLD),
    'Simple', 'Complex'
)

_g2_data = data.loc[mask_strong]
_g2_counts = _g2_data.groupby(['family_id', 'gate2']).size().unstack(fill_value=0)
_g2_counts = _g2_counts.reindex(columns=['Simple', 'Complex'], fill_value=0).sort_index()
_g2_totals = _g2_counts.sum(axis=1)
_g2 = pd.DataFrame(index=_g2_counts.index)
_g2['family_name'] = _g2.index.map(lambda f: FAMILY_CATALOGUE.get(f, {}).get('name', ''))
_g2['Total strong'] = [count_percent(n, n) for n in _g2_totals]
for col in _g2_counts.columns:
    _g2[col] = [count_percent(n, total) for n, total in zip(_g2_counts[col], _g2_totals)]
print('=== Gate 2: Per-family Simple vs Complex (strong_global only) ===')
display(_g2)
print(f'\nOverall strong: {count_percent(_g2_data["gate2"].eq("Simple").sum(), len(_g2_data))} Simple / '
      f'{count_percent(_g2_data["gate2"].eq("Complex").sum(), len(_g2_data))} Complex')

=== Gate 2: Per-family Simple vs Complex (strong_global only) ===

,family_name,Total strong,Simple,Complex
family_id,,,,
F01,Linear positive,"11,756 (100.0%)","11,756 (100.0%)",0 (0.0%)
F03,Power convex positive,"10,576 (100.0%)","10,576 (100.0%)",0 (0.0%)
F05,Power concave positive,"11,057 (100.0%)","11,057 (100.0%)",0 (0.0%)
F07,Saturation positive,"2,936 (100.0%)","2,178 (74.2%)",758 (25.8%)
F13,S-curve positive,"11,933 (100.0%)","11,931 (100.0%)",2 (0.0%)
F15,Threshold positive,"12,566 (100.0%)","9,872 (78.6%)","2,694 (21.4%)"
F18,Quadratic valley (U),"10,290 (100.0%)","5,690 (55.3%)","4,600 (44.7%)"
F21,Cubic,"6,578 (100.0%)","3,099 (47.1%)","3,479 (52.9%)"
F22,Oscillation,"11,997 (100.0%)",0 (0.0%),"11,997 (100.0%)"
F23,Two Lines,"2,412 (100.0%)",27 (1.1%),"2,385 (98.9%)"
F25,Multi-regime threshold,190 (100.0%),0 (0.0%),190 (100.0%)
F26,Windowed threshold,171 (100.0%),0 (0.0%),171 (100.0%)

Overall strong: 66,186 (71.6%) Simple / 26,276 (28.4%) Complex

## Simple path — shape classification

Two-step cascade for **Simple** cases:

1. **Power-law fit**: y = a·x^b + c (R² ≥ 0.90)
   - |b − 1| ≤ 0.05 → **Line**
   - Otherwise a·b·(b−1) sign → **Concave** / **Convex**
2. **Cubic fit** (only when R² < 0.90):
   - ≥ 2 interior turning points → **Cubic**
   - Otherwise → **S-curve/Threshold**

In [6]:
def _power_law(x, a, b, c):
    return a * np.power(np.maximum(x, 1e-10), b) + c


def _fit_power_law(x, y):
    valid = np.isfinite(x) & np.isfinite(y) & (x > 1e-6)
    if valid.sum() < 10:
        return None
    x, y = x[valid], y[valid]
    slope = np.polyfit(x, y, 1)[0]
    a0 = slope
    for b0 in [1.0, 0.5, 2.0, 0.3, 3.0]:
        try:
            popt, _ = curve_fit(
                _power_law, x, y, p0=[a0, b0, np.median(y)],
                maxfev=5000,
                bounds=([-np.inf, 0.05, -np.inf], [np.inf, 8.0, np.inf]),
            )
            y_pred = _power_law(x, *popt)
            ss_res = np.sum((y - y_pred) ** 2)
            ss_tot = np.sum((y - y.mean()) ** 2)
            r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0
            if r2 >= 0:
                return (*popt, r2)
        except (RuntimeError, ValueError):
            continue
    return None


def _fit_cubic(x, y):
    valid = np.isfinite(x) & np.isfinite(y)
    if valid.sum() < 10:
        return None
    x, y = x[valid], y[valid]
    try:
        coeffs = np.polyfit(x, y, 3)
        y_pred = np.polyval(coeffs, x)
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - y.mean()) ** 2)
        r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0
        return coeffs, r2
    except (np.RankWarning, np.linalg.LinAlgError):
        return None


def _count_turning_points(coeffs):
    """Count interior turning points of cubic in [0.05, 0.95]."""
    deriv = np.polyder(coeffs)
    roots = np.roots(deriv)
    real_roots = roots[np.isreal(roots)].real
    interior = real_roots[(real_roots >= 0.05) & (real_roots <= 0.95)]
    return len(interior), np.sort(interior)


def classify_simple_path(x, y):
    """Simple path: power-law → cubic cascade.
    Step 1: Power-law R² >= configured threshold → line / concave / convex
    Step 2: Cubic → >=2 turning points → cubic, otherwise → S-curve/threshold
    """
    # ── Step 1: Power-law ──
    pw = _fit_power_law(x, y)
    if pw is not None:
        a, b, c, r2 = pw
        if r2 >= R2_POWER_THRESHOLD:
            ab = a * b
            direction = 'positive' if ab > 0 else 'negative'
            details = {'step': 'power_law', 'a': a, 'b': b, 'c': c, 'r2': r2}
            if abs(b - 1) <= LINEAR_B_TOLERANCE:
                return f'{direction}_line', details
            curvature = a * b * (b - 1)
            if curvature < 0:
                return f'{direction}_concave', details
            else:
                return f'{direction}_convex', details

    # ── Step 2: Cubic (R² < 0.90) ──
    cb = _fit_cubic(x, y)
    if cb is None:
        return 'simple_other', {'step': 'failed'}

    coeffs, r2_cubic = cb
    n_tp, tp_locs = _count_turning_points(coeffs)
    direction_val = float(np.polyval(coeffs, 1.0) - np.polyval(coeffs, 0.0))
    direction = 'positive' if direction_val >= 0 else 'negative'
    details = {'step': 'cubic', 'coeffs': coeffs.tolist(), 'r2': r2_cubic, 'n_tp': n_tp}

    if n_tp >= 2:
        return 'cubic_two_turning_point', details

    # Otherwise → S-curve/threshold
    return f'{direction}_s_threshold', details

print('Simple path helpers defined.')

Simple path helpers defined.

## Run full classification

In [7]:
import time

pt_idx = data['_pt_idx'].values
shape_labels = np.full(len(data), '', dtype=object)
shape_details = np.full(len(data), '', dtype=object)

mask_intermediate = data['gate1'] == 'intermediate_global'
mask_no_global = data['gate1'] == 'no_global'
shape_labels[mask_intermediate.values] = 'intermediate_global'
shape_labels[mask_no_global.values] = 'no_global'
shape_details[mask_intermediate.values] = '{}'
shape_details[mask_no_global.values] = '{}'

mask_simple = (data['gate2'] == 'Simple').values
mask_complex = (data['gate2'] == 'Complex').values
idx_simple = np.where(mask_simple)[0]

print(f'To classify: {len(idx_simple):,} Simple')
print(f'Complex (not sub-classified): {mask_complex.sum():,}')
print(f'Skipped: {mask_intermediate.sum():,} intermediate + {mask_no_global.sum():,} no_global')

t0 = time.time()
for i in tqdm(idx_simple, desc='Simple path'):
    pi = pt_idx[i]
    x = x_all[pi].astype(np.float64)
    y = y_all[pi].astype(np.float64)
    label, details = classify_simple_path(x, y)
    shape_labels[i] = label
    shape_details[i] = json.dumps(details, default=str)
print(f'Simple path: {len(idx_simple):,} cases in {time.time() - t0:.1f}s')

shape_labels[mask_complex] = 'complex'
shape_details[mask_complex] = '{}'

data['shape_label'] = shape_labels
data['shape_details'] = shape_details

SHAPE_TO_BROAD = {
    'positive_line': 'line', 'negative_line': 'line',
    'positive_concave': 'concave', 'negative_concave': 'concave',
    'positive_convex': 'convex', 'negative_convex': 'convex',
    'cubic_two_turning_point': 'cubic',
    'positive_s_threshold': 'S/threshold', 'negative_s_threshold': 'S/threshold',
    'simple_other': 'other',
}
BROAD_ORDER = ['line', 'concave', 'convex', 'cubic', 'S/threshold', 'other']
data['broad_shape'] = data['shape_label'].map(SHAPE_TO_BROAD)

_simple = data.loc[mask_simple].copy()
_simple['broad_shape'] = _simple['broad_shape'].fillna('other')

# Each stage table contains only the cases that actually entered that stage.
ROUTING_FAMILIES = ['F01', 'F03', 'F05', 'F13', 'F15', 'F21']
POWER_ROUTE_ORDER = ['Linear', 'Concave', 'Convex', 'Enter cubic/S/Threshold branch']
POWER_ROUTE_EXPECTED = {
    'F01': 'Linear',
    'F03': 'Convex',
    'F05': 'Concave',
    'F13': 'Enter cubic/S/Threshold branch',
    'F15': 'Enter cubic/S/Threshold branch',
    'F21': 'Enter cubic/S/Threshold branch',
}

power_routing = _simple[_simple['family_id'].isin(ROUTING_FAMILIES)].copy()
power_routing['power_route'] = power_routing['broad_shape'].map({
    'line': 'Linear',
    'concave': 'Concave',
    'convex': 'Convex',
}).fillna('Enter cubic/S/Threshold branch')
power_routing['expected_power_route'] = power_routing['family_id'].map(POWER_ROUTE_EXPECTED)
power_routing['route_correct'] = (
    power_routing['power_route'] == power_routing['expected_power_route']
)

power_counts = power_routing.groupby(['family_id', 'power_route']).size().unstack(fill_value=0)
power_counts = power_counts.reindex(
    index=ROUTING_FAMILIES, columns=POWER_ROUTE_ORDER, fill_value=0
)
power_totals = power_counts.sum(axis=1)
power_correct = power_routing.groupby('family_id')['route_correct'].sum().reindex(
    ROUTING_FAMILIES, fill_value=0
)
power_table = pd.DataFrame({
    'Family ID': ROUTING_FAMILIES,
    'Family': [FAMILY_CATALOGUE[f]['name'] for f in ROUTING_FAMILIES],
    'Total': [f'{int(n):,}' for n in power_totals],
})
for route in POWER_ROUTE_ORDER:
    power_table[route] = [
        count_percent(power_counts.loc[f, route], power_totals.loc[f])
        for f in ROUTING_FAMILIES
    ]
power_table['Accuracy'] = [
    (
        f'{int(power_correct.loc[f]):,}/{int(power_totals.loc[f]):,} '
        f'({power_correct.loc[f] / power_totals.loc[f]:.1%})'
    ) if power_totals.loc[f] else 'N/A'
    for f in ROUTING_FAMILIES
]

power_overall_correct = int(power_routing['route_correct'].sum())
power_overall_total = len(power_routing)
power_overall = {
    'Family ID': 'Overall',
    'Family': 'All six families',
    'Total': f'{power_overall_total:,}',
    **{
        route: count_percent((power_routing['power_route'] == route).sum(), power_overall_total)
        for route in POWER_ROUTE_ORDER
    },
    'Accuracy': (
        f'{power_overall_correct:,}/{power_overall_total:,} '
        f'({power_overall_correct / power_overall_total:.1%})'
    ),
}
power_table = pd.concat([power_table, pd.DataFrame([power_overall])], ignore_index=True)

print(
    f'\n=== Power-law routing gate: R² >= {R2_POWER_THRESHOLD:.2f}, '
    f'|b−1| <= {LINEAR_B_TOLERANCE:.2f} ==='
)
display(power_table)
print(
    f'Routing accuracy: {power_overall_correct:,}/{power_overall_total:,} '
    f'({power_overall_correct / power_overall_total:.1%})'
)

# Next gate: only cases routed out of the power-law gate.
next_gate = power_routing[
    power_routing['power_route'].eq('Enter cubic/S/Threshold branch')
].copy()
NEXT_ROUTE_ORDER = ['Cubic', 'Enter S/Threshold gate', 'Other/Uncertain']
next_gate['next_route'] = next_gate['broad_shape'].map({
    'cubic': 'Cubic',
    'S/threshold': 'Enter S/Threshold gate',
    'other': 'Other/Uncertain',
}).fillna('Other/Uncertain')
NEXT_ROUTE_EXPECTED = {
    'F13': 'Enter S/Threshold gate',
    'F15': 'Enter S/Threshold gate',
    'F21': 'Cubic',
}
next_gate['expected_next_route'] = next_gate['family_id'].map(NEXT_ROUTE_EXPECTED)
next_gate['route_correct'] = next_gate['next_route'] == next_gate['expected_next_route']
next_families = [f for f in ROUTING_FAMILIES if (next_gate['family_id'] == f).any()]
next_counts = next_gate.groupby(['family_id', 'next_route']).size().unstack(fill_value=0)
next_counts = next_counts.reindex(
    index=next_families, columns=NEXT_ROUTE_ORDER, fill_value=0
)
next_totals = next_counts.sum(axis=1)
next_correct = next_gate.groupby('family_id')['route_correct'].sum().reindex(
    next_families, fill_value=0
)
next_table = pd.DataFrame({
    'Family ID': next_families,
    'Family': [FAMILY_CATALOGUE[f]['name'] for f in next_families],
    'Total entering gate': [f'{int(n):,}' for n in next_totals],
})
for route in NEXT_ROUTE_ORDER:
    next_table[route] = [
        count_percent(next_counts.loc[f, route], next_totals.loc[f])
        for f in next_families
    ]
next_table['Accuracy'] = [
    (
        f'{int(next_correct.loc[f]):,}/{int(next_totals.loc[f]):,} '
        f'({next_correct.loc[f] / next_totals.loc[f]:.1%})'
    ) if next_totals.loc[f] else 'N/A'
    for f in next_families
]

next_overall_correct = int(next_gate['route_correct'].sum())
next_overall_total = len(next_gate)
next_overall = {
    'Family ID': 'Overall',
    'Family': 'All cases entering this gate',
    'Total entering gate': f'{next_overall_total:,}',
    **{
        route: count_percent((next_gate['next_route'] == route).sum(), next_overall_total)
        for route in NEXT_ROUTE_ORDER
    },
    'Accuracy': (
        f'{next_overall_correct:,}/{next_overall_total:,} '
        f'({next_overall_correct / next_overall_total:.1%})'
    ),
}
next_table = pd.concat([next_table, pd.DataFrame([next_overall])], ignore_index=True)

print('\n=== Cubic turning-point gate (only cases entering from the previous gate) ===')
display(next_table)
print(
    f'Gate accuracy: {next_overall_correct:,}/{next_overall_total:,} '
    f'({next_overall_correct / next_overall_total:.1%})'
)

power_table.to_csv(OUT_DIR / 'power_routing_table.csv', index=False)
next_table.to_csv(OUT_DIR / 'cubic_turning_point_gate_table.csv', index=False)

To classify: 66,186 Simple
Complex (not sub-classified): 26,276
Skipped: 32,706 intermediate + 210,792 no_global

Simple path:   0%|          | 0/66186 [00:00<?, ?it/s]

Simple path:   0%|          | 101/66186 [00:00<01:05, 1003.13it/s]

Simple path:   0%|          | 211/66186 [00:00<01:02, 1058.51it/s]

Simple path:   0%|          | 330/66186 [00:00<00:59, 1115.48it/s]

Simple path:   1%|          | 451/66186 [00:00<00:57, 1151.96it/s]

Simple path:   1%|          | 567/66186 [00:00<00:57, 1140.32it/s]

Simple path:   1%|          | 683/66186 [00:00<00:57, 1146.59it/s]

Simple path:   1%|          | 801/66186 [00:00<00:56, 1155.28it/s]

Simple path:   1%|▏         | 921/66186 [00:00<00:55, 1166.62it/s]

Simple path:   2%|▏         | 1038/66186 [00:00<00:56, 1161.18it/s]

Simple path:   2%|▏         | 1155/66186 [00:01<00:56, 1160.74it/s]

Simple path:   2%|▏         | 1272/66186 [00:01<00:55, 1160.98it/s]

Simple path:   2%|▏         | 1389/66186 [00:01<00:55, 1159.41it/s]

Simple path:   2%|▏         | 1505/66186 [00:01<00:56, 1147.60it/s]

Simple path:   2%|▏         | 1620/66186 [00:01<00:56, 1135.51it/s]

Simple path:   3%|▎         | 1736/66186 [00:01<00:56, 1141.47it/s]

Simple path:   3%|▎         | 1854/66186 [00:01<00:55, 1151.65it/s]

Simple path:   3%|▎         | 1973/66186 [00:01<00:55, 1161.78it/s]

Simple path:   3%|▎         | 2090/66186 [00:01<00:55, 1146.37it/s]

Simple path:   3%|▎         | 2207/66186 [00:01<00:55, 1150.71it/s]

Simple path:   4%|▎         | 2327/66186 [00:02<00:54, 1163.20it/s]

Simple path:   4%|▎         | 2449/66186 [00:02<00:54, 1179.26it/s]

Simple path:   4%|▍         | 2567/66186 [00:02<00:55, 1148.90it/s]

Simple path:   4%|▍         | 2683/66186 [00:02<00:55, 1143.37it/s]

Simple path:   4%|▍         | 2800/66186 [00:02<00:55, 1149.38it/s]

Simple path:   4%|▍         | 2916/66186 [00:02<00:55, 1148.90it/s]

Simple path:   5%|▍         | 3031/66186 [00:02<00:56, 1121.16it/s]

Simple path:   5%|▍         | 3145/66186 [00:02<00:56, 1124.18it/s]

Simple path:   5%|▍         | 3263/66186 [00:02<00:55, 1137.72it/s]

Simple path:   5%|▌         | 3383/66186 [00:02<00:54, 1153.26it/s]

Simple path:   5%|▌         | 3499/66186 [00:03<00:54, 1141.51it/s]

Simple path:   5%|▌         | 3617/66186 [00:03<00:54, 1152.19it/s]

Simple path:   6%|▌         | 3733/66186 [00:03<00:54, 1145.43it/s]

Simple path:   6%|▌         | 3849/66186 [00:03<00:54, 1149.56it/s]

Simple path:   6%|▌         | 3965/66186 [00:03<00:54, 1144.63it/s]

Simple path:   6%|▌         | 4080/66186 [00:03<00:54, 1142.90it/s]

Simple path:   6%|▋         | 4195/66186 [00:03<00:54, 1131.16it/s]

Simple path:   7%|▋         | 4312/66186 [00:03<00:54, 1141.51it/s]

Simple path:   7%|▋         | 4431/66186 [00:03<00:53, 1153.15it/s]

Simple path:   7%|▋         | 4547/66186 [00:03<00:54, 1130.60it/s]

Simple path:   7%|▋         | 4663/66186 [00:04<00:54, 1137.51it/s]

Simple path:   7%|▋         | 4778/66186 [00:04<00:53, 1138.19it/s]

Simple path:   7%|▋         | 4901/66186 [00:04<00:52, 1161.87it/s]

Simple path:   8%|▊         | 5018/66186 [00:04<00:53, 1140.03it/s]

Simple path:   8%|▊         | 5134/66186 [00:04<00:53, 1143.63it/s]

Simple path:   8%|▊         | 5253/66186 [00:04<00:52, 1155.03it/s]

Simple path:   8%|▊         | 5375/66186 [00:04<00:51, 1172.90it/s]

Simple path:   8%|▊         | 5493/66186 [00:04<00:52, 1147.54it/s]

Simple path:   8%|▊         | 5609/66186 [00:04<00:52, 1150.07it/s]

Simple path:   9%|▊         | 5728/66186 [00:04<00:52, 1159.60it/s]

Simple path:   9%|▉         | 5850/66186 [00:05<00:51, 1175.15it/s]

Simple path:   9%|▉         | 5968/66186 [00:05<00:51, 1160.48it/s]

Simple path:   9%|▉         | 6085/66186 [00:05<00:54, 1099.28it/s]

Simple path:   9%|▉         | 6196/66186 [00:05<00:55, 1073.40it/s]

Simple path:  10%|▉         | 6316/66186 [00:05<00:54, 1106.60it/s]

Simple path:  10%|▉         | 6428/66186 [00:05<00:54, 1104.68it/s]

Simple path:  10%|▉         | 6541/66186 [00:05<00:53, 1109.63it/s]

Simple path:  10%|█         | 6659/66186 [00:05<00:52, 1127.58it/s]

Simple path:  10%|█         | 6776/66186 [00:05<00:52, 1138.53it/s]

Simple path:  10%|█         | 6891/66186 [00:06<00:52, 1137.55it/s]

Simple path:  11%|█         | 7005/66186 [00:06<00:52, 1133.02it/s]

Simple path:  11%|█         | 7119/66186 [00:06<00:52, 1132.48it/s]

Simple path:  11%|█         | 7235/66186 [00:06<00:51, 1139.68it/s]

Simple path:  11%|█         | 7353/66186 [00:06<00:51, 1150.88it/s]

Simple path:  11%|█▏        | 7469/66186 [00:06<00:52, 1123.82it/s]

Simple path:  11%|█▏        | 7583/66186 [00:06<00:51, 1127.47it/s]

Simple path:  12%|█▏        | 7698/66186 [00:06<00:51, 1132.59it/s]

Simple path:  12%|█▏        | 7817/66186 [00:06<00:50, 1148.08it/s]

Simple path:  12%|█▏        | 7932/66186 [00:06<00:51, 1129.12it/s]

Simple path:  12%|█▏        | 8048/66186 [00:07<00:51, 1136.57it/s]

Simple path:  12%|█▏        | 8162/66186 [00:07<00:51, 1136.31it/s]

Simple path:  13%|█▎        | 8280/66186 [00:07<00:50, 1148.52it/s]

Simple path:  13%|█▎        | 8395/66186 [00:07<00:52, 1108.84it/s]

Simple path:  13%|█▎        | 8511/66186 [00:07<00:51, 1122.50it/s]

Simple path:  13%|█▎        | 8627/66186 [00:07<00:50, 1130.79it/s]

Simple path:  13%|█▎        | 8747/66186 [00:07<00:49, 1149.49it/s]

Simple path:  13%|█▎        | 8863/66186 [00:07<00:50, 1139.27it/s]

Simple path:  14%|█▎        | 8979/66186 [00:07<00:50, 1142.72it/s]

Simple path:  14%|█▎        | 9099/66186 [00:07<00:49, 1158.15it/s]

Simple path:  14%|█▍        | 9219/66186 [00:08<00:48, 1169.55it/s]

Simple path:  14%|█▍        | 9337/66186 [00:08<00:48, 1170.62it/s]

Simple path:  14%|█▍        | 9455/66186 [00:08<00:49, 1153.98it/s]

Simple path:  14%|█▍        | 9572/66186 [00:08<00:48, 1158.37it/s]

Simple path:  15%|█▍        | 9691/66186 [00:08<00:48, 1164.82it/s]

Simple path:  15%|█▍        | 9811/66186 [00:08<00:48, 1173.44it/s]

Simple path:  15%|█▌        | 9929/66186 [00:08<00:48, 1148.72it/s]

Simple path:  15%|█▌        | 10046/66186 [00:08<00:48, 1152.72it/s]

Simple path:  15%|█▌        | 10166/66186 [00:08<00:48, 1165.91it/s]

Simple path:  16%|█▌        | 10286/66186 [00:08<00:47, 1175.21it/s]

Simple path:  16%|█▌        | 10404/66186 [00:09<00:48, 1143.86it/s]

Simple path:  16%|█▌        | 10521/66186 [00:09<00:48, 1148.81it/s]

Simple path:  16%|█▌        | 10637/66186 [00:09<00:48, 1151.36it/s]

Simple path:  16%|█▋        | 10757/66186 [00:09<00:47, 1165.50it/s]

Simple path:  16%|█▋        | 10874/66186 [00:09<00:48, 1142.06it/s]

Simple path:  17%|█▋        | 10990/66186 [00:09<00:48, 1146.82it/s]

Simple path:  17%|█▋        | 11108/66186 [00:09<00:47, 1154.53it/s]

Simple path:  17%|█▋        | 11227/66186 [00:09<00:47, 1163.88it/s]

Simple path:  17%|█▋        | 11344/66186 [00:09<00:47, 1154.66it/s]

Simple path:  17%|█▋        | 11460/66186 [00:10<00:47, 1156.15it/s]

Simple path:  17%|█▋        | 11579/66186 [00:10<00:46, 1164.62it/s]

Simple path:  18%|█▊        | 11705/66186 [00:10<00:45, 1190.63it/s]

Simple path:  18%|█▊        | 11825/66186 [00:10<00:49, 1103.67it/s]

Simple path:  18%|█▊        | 11937/66186 [00:10<00:53, 1012.02it/s]

Simple path:  18%|█▊        | 12041/66186 [00:10<00:56, 957.95it/s]

Simple path:  18%|█▊        | 12139/66186 [00:10<00:58, 924.79it/s]

Simple path:  18%|█▊        | 12233/66186 [00:10<00:59, 901.82it/s]

Simple path:  19%|█▊        | 12324/66186 [00:10<01:01, 878.65it/s]

Simple path:  19%|█▉        | 12413/66186 [00:11<01:02, 860.69it/s]

Simple path:  19%|█▉        | 12500/66186 [00:11<01:03, 848.94it/s]

Simple path:  19%|█▉        | 12586/66186 [00:11<01:03, 839.77it/s]

Simple path:  19%|█▉        | 12671/66186 [00:11<01:04, 825.75it/s]

Simple path:  19%|█▉        | 12754/66186 [00:11<01:06, 800.66it/s]

Simple path:  19%|█▉        | 12835/66186 [00:11<01:08, 783.10it/s]

Simple path:  20%|█▉        | 12914/66186 [00:11<01:08, 773.52it/s]

Simple path:  20%|█▉        | 12992/66186 [00:11<01:09, 767.42it/s]

Simple path:  20%|█▉        | 13069/66186 [00:11<01:09, 761.67it/s]

Simple path:  20%|█▉        | 13149/66186 [00:11<01:08, 772.49it/s]

Simple path:  20%|█▉        | 13227/66186 [00:12<01:11, 744.01it/s]

Simple path:  20%|██        | 13302/66186 [00:12<01:12, 730.20it/s]

Simple path:  20%|██        | 13376/66186 [00:12<01:13, 719.30it/s]

Simple path:  20%|██        | 13449/66186 [00:12<01:23, 627.98it/s]

Simple path:  20%|██        | 13528/66186 [00:12<01:18, 668.15it/s]

Simple path:  21%|██        | 13607/66186 [00:12<01:15, 699.45it/s]

Simple path:  21%|██        | 13685/66186 [00:12<01:12, 719.21it/s]

Simple path:  21%|██        | 13762/66186 [00:12<01:11, 733.10it/s]

Simple path:  21%|██        | 13837/66186 [00:13<01:26, 602.51it/s]

Simple path:  21%|██        | 13911/66186 [00:13<01:22, 635.40it/s]

Simple path:  21%|██        | 13983/66186 [00:13<01:19, 656.21it/s]

Simple path:  21%|██        | 14054/66186 [00:13<01:17, 669.08it/s]

Simple path:  21%|██▏       | 14125/66186 [00:13<01:16, 679.01it/s]

Simple path:  21%|██▏       | 14195/66186 [00:13<01:16, 681.89it/s]

Simple path:  22%|██▏       | 14265/66186 [00:13<01:15, 687.07it/s]

Simple path:  22%|██▏       | 14336/66186 [00:13<01:15, 691.06it/s]

Simple path:  22%|██▏       | 14416/66186 [00:13<01:11, 720.71it/s]

Simple path:  22%|██▏       | 14498/66186 [00:13<01:09, 747.71it/s]

Simple path:  22%|██▏       | 14578/66186 [00:14<01:07, 762.27it/s]

Simple path:  22%|██▏       | 14658/66186 [00:14<01:06, 773.17it/s]

Simple path:  22%|██▏       | 14740/66186 [00:14<01:05, 784.65it/s]

Simple path:  22%|██▏       | 14820/66186 [00:14<01:05, 788.91it/s]

Simple path:  23%|██▎       | 14899/66186 [00:14<01:05, 779.88it/s]

Simple path:  23%|██▎       | 14978/66186 [00:14<01:06, 770.50it/s]

Simple path:  23%|██▎       | 15056/66186 [00:14<01:06, 764.17it/s]

Simple path:  23%|██▎       | 15133/66186 [00:14<01:07, 757.84it/s]

Simple path:  23%|██▎       | 15209/66186 [00:14<01:08, 747.26it/s]

Simple path:  23%|██▎       | 15284/66186 [00:14<01:09, 734.01it/s]

Simple path:  23%|██▎       | 15358/66186 [00:15<01:10, 725.75it/s]

Simple path:  23%|██▎       | 15431/66186 [00:15<01:10, 715.79it/s]

Simple path:  23%|██▎       | 15503/66186 [00:15<01:11, 710.21it/s]

Simple path:  24%|██▎       | 15575/66186 [00:15<01:11, 706.89it/s]

Simple path:  24%|██▎       | 15646/66186 [00:15<01:12, 697.21it/s]

Simple path:  24%|██▍       | 15724/66186 [00:15<01:10, 720.73it/s]

Simple path:  24%|██▍       | 15806/66186 [00:15<01:07, 749.54it/s]

Simple path:  24%|██▍       | 15886/66186 [00:15<01:06, 762.10it/s]

Simple path:  24%|██▍       | 15966/66186 [00:15<01:05, 772.12it/s]

Simple path:  24%|██▍       | 16046/66186 [00:16<01:04, 777.79it/s]

Simple path:  24%|██▍       | 16125/66186 [00:16<01:04, 780.69it/s]

Simple path:  24%|██▍       | 16204/66186 [00:16<01:04, 771.59it/s]

Simple path:  25%|██▍       | 16282/66186 [00:16<01:04, 768.29it/s]

Simple path:  25%|██▍       | 16359/66186 [00:16<01:06, 754.57it/s]

Simple path:  25%|██▍       | 16435/66186 [00:16<01:06, 747.72it/s]

Simple path:  25%|██▍       | 16510/66186 [00:16<01:06, 741.80it/s]

Simple path:  25%|██▌       | 16585/66186 [00:16<01:07, 737.34it/s]

Simple path:  25%|██▌       | 16659/66186 [00:16<01:07, 730.42it/s]

Simple path:  25%|██▌       | 16733/66186 [00:16<01:08, 726.73it/s]

Simple path:  25%|██▌       | 16806/66186 [00:17<01:08, 723.61it/s]

Simple path:  26%|██▌       | 16879/66186 [00:17<01:08, 721.15it/s]

Simple path:  26%|██▌       | 16952/66186 [00:17<01:09, 711.96it/s]

Simple path:  26%|██▌       | 17031/66186 [00:17<01:07, 732.34it/s]

Simple path:  26%|██▌       | 17112/66186 [00:17<01:05, 752.20it/s]

Simple path:  26%|██▌       | 17192/66186 [00:17<01:04, 764.85it/s]

Simple path:  26%|██▌       | 17272/66186 [00:17<01:03, 774.65it/s]

Simple path:  26%|██▌       | 17353/66186 [00:17<01:02, 782.58it/s]

Simple path:  26%|██▋       | 17433/66186 [00:17<01:02, 785.42it/s]

Simple path:  26%|██▋       | 17512/66186 [00:17<01:02, 773.70it/s]

Simple path:  27%|██▋       | 17590/66186 [00:18<01:03, 765.03it/s]

Simple path:  27%|██▋       | 17667/66186 [00:18<01:03, 758.18it/s]

Simple path:  27%|██▋       | 17743/66186 [00:18<01:04, 747.71it/s]

Simple path:  27%|██▋       | 17818/66186 [00:18<01:05, 736.43it/s]

Simple path:  27%|██▋       | 17892/66186 [00:18<01:06, 729.12it/s]

Simple path:  27%|██▋       | 17965/66186 [00:18<01:06, 724.32it/s]

Simple path:  27%|██▋       | 18038/66186 [00:18<01:06, 718.87it/s]

Simple path:  27%|██▋       | 18110/66186 [00:18<01:07, 710.49it/s]

Simple path:  27%|██▋       | 18182/66186 [00:18<01:07, 707.19it/s]

Simple path:  28%|██▊       | 18253/66186 [00:19<01:08, 700.76it/s]

Simple path:  28%|██▊       | 18326/66186 [00:19<01:07, 709.13it/s]

Simple path:  28%|██▊       | 18407/66186 [00:19<01:04, 736.80it/s]

Simple path:  28%|██▊       | 18487/66186 [00:19<01:03, 753.26it/s]

Simple path:  28%|██▊       | 18567/66186 [00:19<01:02, 764.47it/s]

Simple path:  28%|██▊       | 18646/66186 [00:19<01:01, 771.64it/s]

Simple path:  28%|██▊       | 18727/66186 [00:19<01:00, 780.01it/s]

Simple path:  28%|██▊       | 18806/66186 [00:19<01:01, 775.76it/s]

Simple path:  29%|██▊       | 18884/66186 [00:19<01:01, 774.13it/s]

Simple path:  29%|██▊       | 18962/66186 [00:19<01:01, 762.23it/s]

Simple path:  29%|██▉       | 19039/66186 [00:20<01:03, 746.89it/s]

Simple path:  29%|██▉       | 19114/66186 [00:20<01:03, 736.40it/s]

Simple path:  29%|██▉       | 19188/66186 [00:20<01:04, 728.90it/s]

Simple path:  29%|██▉       | 19261/66186 [00:20<01:04, 726.17it/s]

Simple path:  29%|██▉       | 19334/66186 [00:20<01:04, 723.21it/s]

Simple path:  29%|██▉       | 19407/66186 [00:20<01:05, 719.53it/s]

Simple path:  29%|██▉       | 19479/66186 [00:20<01:04, 719.52it/s]

Simple path:  30%|██▉       | 19551/66186 [00:20<01:05, 717.15it/s]

Simple path:  30%|██▉       | 19623/66186 [00:20<01:06, 704.63it/s]

Simple path:  30%|██▉       | 19702/66186 [00:20<01:03, 729.58it/s]

Simple path:  30%|██▉       | 19785/66186 [00:21<01:01, 758.54it/s]

Simple path:  30%|███       | 19867/66186 [00:21<00:59, 775.06it/s]

Simple path:  30%|███       | 19949/66186 [00:21<00:58, 786.82it/s]

Simple path:  30%|███       | 20030/66186 [00:21<00:58, 793.28it/s]

Simple path:  30%|███       | 20110/66186 [00:21<00:58, 793.41it/s]

Simple path:  31%|███       | 20190/66186 [00:21<00:58, 785.70it/s]

Simple path:  31%|███       | 20269/66186 [00:21<00:59, 776.75it/s]

Simple path:  31%|███       | 20347/66186 [00:21<01:00, 763.73it/s]

Simple path:  31%|███       | 20424/66186 [00:21<01:00, 751.40it/s]

Simple path:  31%|███       | 20500/66186 [00:21<01:01, 742.26it/s]

Simple path:  31%|███       | 20575/66186 [00:22<01:02, 733.39it/s]

Simple path:  31%|███       | 20649/66186 [00:22<01:02, 729.20it/s]

Simple path:  31%|███▏      | 20722/66186 [00:22<01:02, 725.99it/s]

Simple path:  31%|███▏      | 20795/66186 [00:22<01:02, 720.82it/s]

Simple path:  32%|███▏      | 20868/66186 [00:22<01:03, 716.19it/s]

Simple path:  32%|███▏      | 20940/66186 [00:22<01:03, 708.97it/s]

Simple path:  32%|███▏      | 21012/66186 [00:22<01:03, 709.75it/s]

Simple path:  32%|███▏      | 21096/66186 [00:22<01:00, 747.24it/s]

Simple path:  32%|███▏      | 21177/66186 [00:22<00:58, 763.78it/s]

Simple path:  32%|███▏      | 21254/66186 [00:23<00:58, 765.61it/s]

Simple path:  32%|███▏      | 21334/66186 [00:23<00:57, 774.55it/s]

Simple path:  32%|███▏      | 21412/66186 [00:23<00:57, 776.08it/s]

Simple path:  32%|███▏      | 21490/66186 [00:23<00:58, 768.75it/s]

Simple path:  33%|███▎      | 21567/66186 [00:23<00:58, 764.56it/s]

Simple path:  33%|███▎      | 21644/66186 [00:23<00:58, 759.73it/s]

Simple path:  33%|███▎      | 21720/66186 [00:23<00:59, 748.93it/s]

Simple path:  33%|███▎      | 21795/66186 [00:23<01:00, 739.55it/s]

Simple path:  33%|███▎      | 21869/66186 [00:23<01:00, 732.10it/s]

Simple path:  33%|███▎      | 21943/66186 [00:23<01:01, 722.18it/s]

Simple path:  33%|███▎      | 22016/66186 [00:24<01:01, 714.80it/s]

Simple path:  33%|███▎      | 22088/66186 [00:24<01:01, 711.35it/s]

Simple path:  33%|███▎      | 22160/66186 [00:24<01:02, 709.40it/s]

Simple path:  34%|███▎      | 22231/66186 [00:24<01:02, 707.28it/s]

Simple path:  34%|███▎      | 22302/66186 [00:24<01:02, 701.32it/s]

Simple path:  34%|███▍      | 22373/66186 [00:24<01:05, 672.18it/s]

Simple path:  34%|███▍      | 22441/66186 [00:24<01:06, 654.10it/s]

Simple path:  34%|███▍      | 22507/66186 [00:24<01:08, 636.92it/s]

Simple path:  34%|███▍      | 22571/66186 [00:24<01:10, 622.63it/s]

Simple path:  34%|███▍      | 22634/66186 [00:25<01:11, 613.12it/s]

Simple path:  34%|███▍      | 22696/66186 [00:25<01:11, 605.42it/s]

Simple path:  34%|███▍      | 22757/66186 [00:25<01:12, 601.60it/s]

Simple path:  34%|███▍      | 22818/66186 [00:25<01:18, 550.17it/s]

Simple path:  35%|███▍      | 22874/66186 [00:25<01:28, 487.88it/s]

Simple path:  35%|███▍      | 22925/66186 [00:25<01:34, 456.14it/s]

Simple path:  35%|███▍      | 22972/66186 [00:25<01:38, 438.67it/s]

Simple path:  35%|███▍      | 23017/66186 [00:25<01:41, 426.03it/s]

Simple path:  35%|███▍      | 23061/66186 [00:25<01:43, 414.68it/s]

Simple path:  35%|███▍      | 23103/66186 [00:26<01:46, 406.23it/s]

Simple path:  35%|███▍      | 23144/66186 [00:26<01:47, 401.16it/s]

Simple path:  35%|███▌      | 23185/66186 [00:26<01:48, 396.09it/s]

Simple path:  35%|███▌      | 23225/66186 [00:26<01:50, 388.43it/s]

Simple path:  35%|███▌      | 23264/66186 [00:26<02:04, 345.06it/s]

Simple path:  35%|███▌      | 23300/66186 [00:26<02:16, 313.27it/s]

Simple path:  35%|███▌      | 23333/66186 [00:26<02:27, 291.20it/s]

Simple path:  35%|███▌      | 23363/66186 [00:26<02:36, 273.90it/s]

Simple path:  35%|███▌      | 23391/66186 [00:27<02:41, 265.60it/s]

Simple path:  35%|███▌      | 23418/66186 [00:27<02:45, 257.65it/s]

Simple path:  35%|███▌      | 23444/66186 [00:27<02:49, 251.65it/s]

Simple path:  35%|███▌      | 23470/66186 [00:27<02:50, 250.64it/s]

Simple path:  35%|███▌      | 23496/66186 [00:27<02:53, 246.75it/s]

Simple path:  36%|███▌      | 23521/66186 [00:27<02:53, 245.83it/s]

Simple path:  36%|███▌      | 23547/66186 [00:27<02:52, 247.44it/s]

Simple path:  36%|███▌      | 23572/66186 [00:27<02:54, 243.70it/s]

Simple path:  36%|███▌      | 23597/66186 [00:27<02:55, 243.10it/s]

Simple path:  36%|███▌      | 23622/66186 [00:28<02:56, 240.75it/s]

Simple path:  36%|███▌      | 23647/66186 [00:28<02:57, 239.03it/s]

Simple path:  36%|███▌      | 23692/66186 [00:28<02:21, 299.58it/s]

Simple path:  36%|███▌      | 23753/66186 [00:28<01:49, 389.03it/s]

Simple path:  36%|███▌      | 23812/66186 [00:28<01:34, 447.90it/s]

Simple path:  36%|███▌      | 23868/66186 [00:28<01:28, 479.19it/s]

Simple path:  36%|███▌      | 23927/66186 [00:28<01:22, 510.61it/s]

Simple path:  36%|███▌      | 23986/66186 [00:28<01:19, 534.04it/s]

Simple path:  36%|███▋      | 24045/66186 [00:28<01:16, 550.17it/s]

Simple path:  36%|███▋      | 24105/66186 [00:28<01:14, 562.49it/s]

Simple path:  37%|███▋      | 24162/66186 [00:29<01:15, 554.01it/s]

Simple path:  37%|███▋      | 24219/66186 [00:29<01:15, 556.78it/s]

Simple path:  37%|███▋      | 24275/66186 [00:29<01:17, 544.06it/s]

Simple path:  37%|███▋      | 24330/66186 [00:29<01:17, 541.14it/s]

Simple path:  37%|███▋      | 24386/66186 [00:29<01:16, 545.17it/s]

Simple path:  37%|███▋      | 24441/66186 [00:29<01:16, 543.41it/s]

Simple path:  37%|███▋      | 24497/66186 [00:29<01:16, 546.61it/s]

Simple path:  37%|███▋      | 24552/66186 [00:29<01:16, 543.11it/s]

Simple path:  37%|███▋      | 24607/66186 [00:29<01:26, 482.83it/s]

Simple path:  37%|███▋      | 24657/66186 [00:30<01:34, 440.46it/s]

Simple path:  37%|███▋      | 24703/66186 [00:30<01:39, 416.20it/s]

Simple path:  37%|███▋      | 24746/66186 [00:30<01:43, 400.35it/s]

Simple path:  37%|███▋      | 24787/66186 [00:30<01:46, 389.26it/s]

Simple path:  38%|███▊      | 24827/66186 [00:30<01:47, 383.50it/s]

Simple path:  38%|███▊      | 24866/66186 [00:30<01:49, 378.86it/s]

Simple path:  38%|███▊      | 24905/66186 [00:30<01:51, 371.26it/s]

Simple path:  38%|███▊      | 24943/66186 [00:30<01:52, 366.26it/s]

Simple path:  38%|███▊      | 24980/66186 [00:30<01:53, 363.17it/s]

Simple path:  38%|███▊      | 25035/66186 [00:31<01:39, 414.25it/s]

Simple path:  38%|███▊      | 25101/66186 [00:31<01:24, 484.23it/s]

Simple path:  38%|███▊      | 25167/66186 [00:31<01:16, 533.45it/s]

Simple path:  38%|███▊      | 25232/66186 [00:31<01:12, 565.52it/s]

Simple path:  38%|███▊      | 25297/66186 [00:31<01:09, 588.11it/s]

Simple path:  38%|███▊      | 25361/66186 [00:31<01:07, 602.66it/s]

Simple path:  38%|███▊      | 25425/66186 [00:31<01:06, 612.02it/s]

Simple path:  39%|███▊      | 25487/66186 [00:31<01:06, 613.96it/s]

Simple path:  39%|███▊      | 25552/66186 [00:31<01:05, 621.99it/s]

Simple path:  39%|███▊      | 25616/66186 [00:31<01:04, 627.13it/s]

Simple path:  39%|███▉      | 25679/66186 [00:32<01:04, 627.31it/s]

Simple path:  39%|███▉      | 25742/66186 [00:32<01:04, 627.29it/s]

Simple path:  39%|███▉      | 25807/66186 [00:32<01:04, 630.73it/s]

Simple path:  39%|███▉      | 25871/66186 [00:32<01:04, 626.99it/s]

Simple path:  39%|███▉      | 25934/66186 [00:32<01:05, 610.69it/s]

Simple path:  39%|███▉      | 25996/66186 [00:32<01:11, 558.22it/s]

Simple path:  39%|███▉      | 26053/66186 [00:32<01:14, 535.86it/s]

Simple path:  39%|███▉      | 26108/66186 [00:32<01:18, 512.85it/s]

Simple path:  40%|███▉      | 26160/66186 [00:32<01:20, 495.96it/s]

Simple path:  40%|███▉      | 26210/66186 [00:33<01:22, 481.64it/s]

Simple path:  40%|███▉      | 26259/66186 [00:33<01:24, 475.11it/s]

Simple path:  40%|███▉      | 26307/66186 [00:33<01:26, 463.67it/s]

Simple path:  40%|███▉      | 26354/66186 [00:33<01:27, 452.67it/s]

Simple path:  40%|███▉      | 26413/66186 [00:33<01:21, 489.41it/s]

Simple path:  40%|████      | 26482/66186 [00:33<01:12, 544.08it/s]

Simple path:  40%|████      | 26552/66186 [00:33<01:07, 587.27it/s]

Simple path:  40%|████      | 26619/66186 [00:33<01:04, 609.75it/s]

Simple path:  40%|████      | 26686/66186 [00:33<01:03, 624.68it/s]

Simple path:  40%|████      | 26751/66186 [00:34<01:02, 630.81it/s]

Simple path:  41%|████      | 26817/66186 [00:34<01:01, 637.70it/s]

Simple path:  41%|████      | 26881/66186 [00:34<01:10, 555.77it/s]

Simple path:  41%|████      | 26942/66186 [00:34<01:09, 568.27it/s]

Simple path:  41%|████      | 27003/66186 [00:34<01:07, 577.52it/s]

Simple path:  41%|████      | 27062/66186 [00:34<01:07, 580.42it/s]

Simple path:  41%|████      | 27127/66186 [00:34<01:05, 599.33it/s]

Simple path:  41%|████      | 27190/66186 [00:34<01:04, 607.48it/s]

Simple path:  41%|████      | 27253/66186 [00:34<01:03, 611.28it/s]

Simple path:  41%|████▏     | 27315/66186 [00:34<01:04, 606.78it/s]

Simple path:  41%|████▏     | 27376/66186 [00:35<01:05, 591.91it/s]

Simple path:  41%|████▏     | 27436/66186 [00:35<01:06, 582.50it/s]

Simple path:  42%|████▏     | 27495/66186 [00:35<01:07, 575.95it/s]

Simple path:  42%|████▏     | 27553/66186 [00:35<01:07, 570.71it/s]

Simple path:  42%|████▏     | 27611/66186 [00:35<01:08, 563.92it/s]

Simple path:  42%|████▏     | 27668/66186 [00:35<01:08, 564.78it/s]

Simple path:  42%|████▏     | 27725/66186 [00:35<01:09, 555.02it/s]

Simple path:  42%|████▏     | 27789/66186 [00:35<01:06, 577.01it/s]

Simple path:  42%|████▏     | 27864/66186 [00:35<01:01, 627.35it/s]

Simple path:  42%|████▏     | 27939/66186 [00:36<00:57, 663.20it/s]

Simple path:  42%|████▏     | 28011/66186 [00:36<00:56, 679.92it/s]

Simple path:  42%|████▏     | 28083/66186 [00:36<00:55, 689.93it/s]

Simple path:  43%|████▎     | 28153/66186 [00:36<00:55, 690.87it/s]

Simple path:  43%|████▎     | 28223/66186 [00:36<00:55, 689.39it/s]

Simple path:  43%|████▎     | 28292/66186 [00:36<00:57, 663.80it/s]

Simple path:  43%|████▎     | 28359/66186 [00:36<01:02, 608.38it/s]

Simple path:  43%|████▎     | 28423/66186 [00:36<01:01, 615.72it/s]

Simple path:  43%|████▎     | 28486/66186 [00:36<01:02, 602.02it/s]

Simple path:  43%|████▎     | 28548/66186 [00:36<01:02, 605.74it/s]

Simple path:  43%|████▎     | 28610/66186 [00:37<01:01, 608.86it/s]

Simple path:  43%|████▎     | 28672/66186 [00:37<01:01, 605.73it/s]

Simple path:  43%|████▎     | 28733/66186 [00:37<01:03, 593.99it/s]

Simple path:  44%|████▎     | 28793/66186 [00:37<01:03, 592.86it/s]

Simple path:  44%|████▎     | 28854/66186 [00:37<01:02, 596.34it/s]

Simple path:  44%|████▎     | 28914/66186 [00:37<01:02, 592.11it/s]

Simple path:  44%|████▍     | 28974/66186 [00:37<01:03, 582.48it/s]

Simple path:  44%|████▍     | 29033/66186 [00:37<01:04, 573.85it/s]

Simple path:  44%|████▍     | 29091/66186 [00:37<01:05, 565.43it/s]

Simple path:  44%|████▍     | 29148/66186 [00:38<01:05, 566.61it/s]

Simple path:  44%|████▍     | 29232/66186 [00:38<00:57, 644.70it/s]

Simple path:  44%|████▍     | 29321/66186 [00:38<00:51, 715.96it/s]

Simple path:  44%|████▍     | 29412/66186 [00:38<00:47, 773.15it/s]

Simple path:  45%|████▍     | 29499/66186 [00:38<00:45, 800.00it/s]

Simple path:  45%|████▍     | 29587/66186 [00:38<00:44, 821.12it/s]

Simple path:  45%|████▍     | 29670/66186 [00:38<00:44, 813.54it/s]

Simple path:  45%|████▍     | 29754/66186 [00:38<00:44, 819.05it/s]

Simple path:  45%|████▌     | 29841/66186 [00:38<00:43, 831.68it/s]

Simple path:  45%|████▌     | 29927/66186 [00:38<00:43, 838.69it/s]

Simple path:  45%|████▌     | 30014/66186 [00:39<00:42, 845.24it/s]

Simple path:  45%|████▌     | 30100/66186 [00:39<00:42, 847.37it/s]

Simple path:  46%|████▌     | 30185/66186 [00:39<00:45, 783.19it/s]

Simple path:  46%|████▌     | 30265/66186 [00:39<00:48, 743.72it/s]

Simple path:  46%|████▌     | 30341/66186 [00:39<00:50, 709.06it/s]

Simple path:  46%|████▌     | 30413/66186 [00:39<00:56, 634.16it/s]

Simple path:  46%|████▌     | 30479/66186 [00:39<00:56, 632.41it/s]

Simple path:  46%|████▌     | 30544/66186 [00:39<00:56, 635.34it/s]

Simple path:  46%|████▋     | 30619/66186 [00:39<00:53, 665.82it/s]

Simple path:  46%|████▋     | 30708/66186 [00:40<00:48, 727.70it/s]

Simple path:  47%|████▋     | 30799/66186 [00:40<00:45, 777.58it/s]

Simple path:  47%|████▋     | 30889/66186 [00:40<00:43, 812.63it/s]

Simple path:  47%|████▋     | 30979/66186 [00:40<00:42, 836.93it/s]

Simple path:  47%|████▋     | 31064/66186 [00:40<00:41, 836.48it/s]

Simple path:  47%|████▋     | 31149/66186 [00:40<00:43, 803.09it/s]

Simple path:  47%|████▋     | 31230/66186 [00:40<00:44, 785.30it/s]

Simple path:  47%|████▋     | 31309/66186 [00:40<00:45, 763.54it/s]

Simple path:  47%|████▋     | 31386/66186 [00:40<00:46, 750.57it/s]

Simple path:  48%|████▊     | 31462/66186 [00:40<00:47, 737.34it/s]

Simple path:  48%|████▊     | 31536/66186 [00:41<00:48, 710.95it/s]

Simple path:  48%|████▊     | 31608/66186 [00:41<00:49, 691.59it/s]

Simple path:  48%|████▊     | 31678/66186 [00:41<00:51, 676.43it/s]

Simple path:  48%|████▊     | 31746/66186 [00:41<00:52, 661.62it/s]

Simple path:  48%|████▊     | 31813/66186 [00:41<00:52, 650.58it/s]

Simple path:  48%|████▊     | 31879/66186 [00:41<00:53, 639.87it/s]

Simple path:  48%|████▊     | 31943/66186 [00:41<00:55, 620.95it/s]

Simple path:  48%|████▊     | 32014/66186 [00:41<00:53, 644.14it/s]

Simple path:  49%|████▊     | 32104/66186 [00:41<00:47, 717.46it/s]

Simple path:  49%|████▊     | 32196/66186 [00:42<00:43, 774.13it/s]

Simple path:  49%|████▉     | 32287/66186 [00:42<00:41, 812.99it/s]

Simple path:  49%|████▉     | 32378/66186 [00:42<00:40, 839.63it/s]

Simple path:  49%|████▉     | 32466/66186 [00:42<00:39, 850.97it/s]

Simple path:  49%|████▉     | 32552/66186 [00:42<00:40, 822.37it/s]

Simple path:  49%|████▉     | 32635/66186 [00:42<00:41, 808.18it/s]

Simple path:  49%|████▉     | 32720/66186 [00:42<00:40, 817.82it/s]

Simple path:  50%|████▉     | 32805/66186 [00:42<00:40, 826.31it/s]

Simple path:  50%|████▉     | 32888/66186 [00:42<00:40, 815.01it/s]

Simple path:  50%|████▉     | 32970/66186 [00:43<00:42, 782.27it/s]

Simple path:  50%|████▉     | 33049/66186 [00:43<00:44, 748.17it/s]

Simple path:  50%|█████     | 33125/66186 [00:43<00:46, 711.63it/s]

Simple path:  50%|█████     | 33197/66186 [00:43<00:47, 690.72it/s]

Simple path:  50%|█████     | 33267/66186 [00:43<00:49, 671.15it/s]

Simple path:  50%|█████     | 33335/66186 [00:43<00:50, 654.94it/s]

Simple path:  50%|█████     | 33401/66186 [00:43<00:56, 578.19it/s]

Simple path:  51%|█████     | 33461/66186 [00:44<01:25, 382.52it/s]

Simple path:  51%|█████     | 33509/66186 [00:44<01:44, 312.45it/s]

Simple path:  51%|█████     | 33549/66186 [00:44<01:58, 276.38it/s]

Simple path:  51%|█████     | 33583/66186 [00:44<02:09, 252.67it/s]

Simple path:  51%|█████     | 33612/66186 [00:44<02:15, 239.83it/s]

Simple path:  51%|█████     | 33639/66186 [00:44<02:22, 228.68it/s]

Simple path:  51%|█████     | 33664/66186 [00:45<02:28, 219.58it/s]

Simple path:  51%|█████     | 33687/66186 [00:45<02:32, 213.70it/s]

Simple path:  51%|█████     | 33709/66186 [00:45<02:36, 207.43it/s]

Simple path:  51%|█████     | 33730/66186 [00:45<02:40, 201.59it/s]

Simple path:  51%|█████     | 33751/66186 [00:45<02:41, 201.11it/s]

Simple path:  51%|█████     | 33772/66186 [00:45<02:43, 198.53it/s]

Simple path:  51%|█████     | 33792/66186 [00:45<02:43, 198.30it/s]

Simple path:  51%|█████     | 33812/66186 [00:45<02:44, 197.16it/s]

Simple path:  51%|█████     | 33832/66186 [00:45<02:44, 196.55it/s]

Simple path:  51%|█████     | 33852/66186 [00:46<02:45, 195.52it/s]

Simple path:  51%|█████     | 33872/66186 [00:46<02:46, 194.33it/s]

Simple path:  51%|█████     | 33892/66186 [00:46<02:46, 193.81it/s]

Simple path:  51%|█████     | 33912/66186 [00:46<02:47, 193.02it/s]

Simple path:  51%|█████▏    | 33932/66186 [00:46<02:45, 194.87it/s]

Simple path:  51%|█████▏    | 33952/66186 [00:46<02:46, 193.97it/s]

Simple path:  51%|█████▏    | 33972/66186 [00:46<02:45, 194.07it/s]

Simple path:  51%|█████▏    | 33992/66186 [00:46<02:46, 193.38it/s]

Simple path:  51%|█████▏    | 34012/66186 [00:46<02:46, 193.55it/s]

Simple path:  51%|█████▏    | 34032/66186 [00:46<02:44, 195.01it/s]

Simple path:  51%|█████▏    | 34052/66186 [00:47<02:45, 194.38it/s]

Simple path:  51%|█████▏    | 34072/66186 [00:47<02:45, 194.55it/s]

Simple path:  52%|█████▏    | 34092/66186 [00:47<02:43, 195.92it/s]

Simple path:  52%|█████▏    | 34112/66186 [00:47<02:43, 196.15it/s]

Simple path:  52%|█████▏    | 34132/66186 [00:47<02:44, 195.28it/s]

Simple path:  52%|█████▏    | 34152/66186 [00:47<02:45, 193.80it/s]

Simple path:  52%|█████▏    | 34172/66186 [00:47<02:45, 192.86it/s]

Simple path:  52%|█████▏    | 34192/66186 [00:47<02:44, 194.60it/s]

Simple path:  52%|█████▏    | 34213/66186 [00:47<02:42, 196.94it/s]

Simple path:  52%|█████▏    | 34233/66186 [00:48<02:41, 197.62it/s]

Simple path:  52%|█████▏    | 34254/66186 [00:48<02:39, 200.14it/s]

Simple path:  52%|█████▏    | 34275/66186 [00:48<02:38, 201.90it/s]

Simple path:  52%|█████▏    | 34296/66186 [00:48<02:36, 203.15it/s]

Simple path:  52%|█████▏    | 34317/66186 [00:48<02:38, 201.20it/s]

Simple path:  52%|█████▏    | 34338/66186 [00:48<02:37, 202.67it/s]

Simple path:  52%|█████▏    | 34359/66186 [00:48<02:36, 203.09it/s]

Simple path:  52%|█████▏    | 34381/66186 [00:48<02:34, 205.57it/s]

Simple path:  52%|█████▏    | 34402/66186 [00:48<02:35, 204.03it/s]

Simple path:  52%|█████▏    | 34425/66186 [00:48<02:30, 211.14it/s]

Simple path:  52%|█████▏    | 34447/66186 [00:49<02:32, 208.35it/s]

Simple path:  52%|█████▏    | 34468/66186 [00:49<02:33, 206.46it/s]

Simple path:  52%|█████▏    | 34490/66186 [00:49<02:32, 208.38it/s]

Simple path:  52%|█████▏    | 34511/66186 [00:49<02:33, 205.90it/s]

Simple path:  52%|█████▏    | 34532/66186 [00:49<02:32, 207.04it/s]

Simple path:  52%|█████▏    | 34553/66186 [00:49<02:38, 199.12it/s]

Simple path:  52%|█████▏    | 34574/66186 [00:49<02:36, 202.18it/s]

Simple path:  52%|█████▏    | 34595/66186 [00:49<02:35, 203.77it/s]

Simple path:  52%|█████▏    | 34617/66186 [00:49<02:33, 205.72it/s]

Simple path:  52%|█████▏    | 34638/66186 [00:49<02:35, 202.35it/s]

Simple path:  52%|█████▏    | 34660/66186 [00:50<02:32, 206.57it/s]

Simple path:  52%|█████▏    | 34681/66186 [00:50<02:35, 202.18it/s]

Simple path:  52%|█████▏    | 34702/66186 [00:50<02:35, 202.90it/s]

Simple path:  52%|█████▏    | 34725/66186 [00:50<02:29, 210.42it/s]

Simple path:  53%|█████▎    | 34750/66186 [00:50<02:22, 221.13it/s]

Simple path:  53%|█████▎    | 34775/66186 [00:50<02:17, 228.19it/s]

Simple path:  53%|█████▎    | 34800/66186 [00:50<02:14, 233.19it/s]

Simple path:  53%|█████▎    | 34825/66186 [00:50<02:12, 237.53it/s]

Simple path:  53%|█████▎    | 34850/66186 [00:50<02:11, 239.19it/s]

Simple path:  53%|█████▎    | 34876/66186 [00:51<02:08, 243.27it/s]

Simple path:  53%|█████▎    | 34901/66186 [00:51<02:09, 242.33it/s]

Simple path:  53%|█████▎    | 34926/66186 [00:51<02:10, 239.20it/s]

Simple path:  53%|█████▎    | 34951/66186 [00:51<02:08, 242.30it/s]

Simple path:  53%|█████▎    | 34976/66186 [00:51<02:07, 244.29it/s]

Simple path:  53%|█████▎    | 35001/66186 [00:51<02:06, 245.96it/s]

Simple path:  53%|█████▎    | 35027/66186 [00:51<02:05, 248.49it/s]

Simple path:  53%|█████▎    | 35052/66186 [00:51<02:05, 248.47it/s]

Simple path:  53%|█████▎    | 35077/66186 [00:51<02:05, 247.39it/s]

Simple path:  53%|█████▎    | 35103/66186 [00:51<02:04, 250.00it/s]

Simple path:  53%|█████▎    | 35129/66186 [00:52<02:04, 250.36it/s]

Simple path:  53%|█████▎    | 35155/66186 [00:52<02:19, 221.68it/s]

Simple path:  53%|█████▎    | 35179/66186 [00:52<02:17, 225.19it/s]

Simple path:  53%|█████▎    | 35205/66186 [00:52<02:12, 234.49it/s]

Simple path:  53%|█████▎    | 35229/66186 [00:52<02:11, 234.95it/s]

Simple path:  53%|█████▎    | 35253/66186 [00:52<02:15, 228.22it/s]

Simple path:  53%|█████▎    | 35278/66186 [00:52<02:13, 231.95it/s]

Simple path:  53%|█████▎    | 35303/66186 [00:52<02:10, 236.25it/s]

Simple path:  53%|█████▎    | 35327/66186 [00:52<02:10, 236.59it/s]

Simple path:  53%|█████▎    | 35352/66186 [00:52<02:09, 238.75it/s]

Simple path:  53%|█████▎    | 35376/66186 [00:53<02:19, 220.66it/s]

Simple path:  53%|█████▎    | 35401/66186 [00:53<02:14, 228.28it/s]

Simple path:  54%|█████▎    | 35426/66186 [00:53<02:12, 232.02it/s]

Simple path:  54%|█████▎    | 35451/66186 [00:53<02:10, 235.10it/s]

Simple path:  54%|█████▎    | 35476/66186 [00:53<02:08, 238.49it/s]

Simple path:  54%|█████▎    | 35500/66186 [00:53<02:09, 236.05it/s]

Simple path:  54%|█████▎    | 35525/66186 [00:53<02:08, 238.35it/s]

Simple path:  54%|█████▎    | 35549/66186 [00:53<02:08, 238.55it/s]

Simple path:  54%|█████▍    | 35583/66186 [00:53<01:54, 266.76it/s]

Simple path:  54%|█████▍    | 35635/66186 [00:54<01:29, 341.07it/s]

Simple path:  54%|█████▍    | 35686/66186 [00:54<01:18, 389.78it/s]

Simple path:  54%|█████▍    | 35738/66186 [00:54<01:11, 427.12it/s]

Simple path:  54%|█████▍    | 35790/66186 [00:54<01:06, 453.83it/s]

Simple path:  54%|█████▍    | 35842/66186 [00:54<01:04, 472.29it/s]

Simple path:  54%|█████▍    | 35895/66186 [00:54<01:02, 487.79it/s]

Simple path:  54%|█████▍    | 35947/66186 [00:54<01:01, 495.07it/s]

Simple path:  54%|█████▍    | 36000/66186 [00:54<00:59, 505.24it/s]

Simple path:  54%|█████▍    | 36051/66186 [00:54<00:59, 502.70it/s]

Simple path:  55%|█████▍    | 36102/66186 [00:54<01:00, 493.81it/s]

Simple path:  55%|█████▍    | 36152/66186 [00:55<01:02, 480.82it/s]

Simple path:  55%|█████▍    | 36201/66186 [00:55<01:03, 475.59it/s]

Simple path:  55%|█████▍    | 36249/66186 [00:55<01:03, 470.11it/s]

Simple path:  55%|█████▍    | 36297/66186 [00:55<01:05, 457.28it/s]

Simple path:  55%|█████▍    | 36343/66186 [00:55<01:05, 452.86it/s]

Simple path:  55%|█████▍    | 36390/66186 [00:55<01:05, 455.99it/s]

Simple path:  55%|█████▌    | 36436/66186 [00:55<01:06, 446.71it/s]

Simple path:  55%|█████▌    | 36481/66186 [00:55<01:07, 442.53it/s]

Simple path:  55%|█████▌    | 36526/66186 [00:55<01:08, 435.44it/s]

Simple path:  55%|█████▌    | 36571/66186 [00:56<01:07, 438.65it/s]

Simple path:  55%|█████▌    | 36615/66186 [00:56<01:09, 425.13it/s]

Simple path:  55%|█████▌    | 36660/66186 [00:56<01:08, 432.05it/s]

Simple path:  55%|█████▌    | 36705/66186 [00:56<01:07, 433.81it/s]

Simple path:  56%|█████▌    | 36749/66186 [00:56<01:07, 434.20it/s]

Simple path:  56%|█████▌    | 36793/66186 [00:56<01:07, 435.39it/s]

Simple path:  56%|█████▌    | 36837/66186 [00:56<01:10, 417.29it/s]

Simple path:  56%|█████▌    | 36879/66186 [00:56<01:16, 383.93it/s]

Simple path:  56%|█████▌    | 36922/66186 [00:56<01:14, 393.52it/s]

Simple path:  56%|█████▌    | 36965/66186 [00:56<01:12, 402.66it/s]

Simple path:  56%|█████▌    | 37008/66186 [00:57<01:11, 409.51it/s]

Simple path:  56%|█████▌    | 37059/66186 [00:57<01:06, 435.97it/s]

Simple path:  56%|█████▌    | 37109/66186 [00:57<01:04, 452.79it/s]

Simple path:  56%|█████▌    | 37160/66186 [00:57<01:02, 467.70it/s]

Simple path:  56%|█████▌    | 37212/66186 [00:57<01:00, 480.98it/s]

Simple path:  56%|█████▋    | 37261/66186 [00:57<01:11, 403.85it/s]

Simple path:  56%|█████▋    | 37306/66186 [00:57<01:09, 415.81it/s]

Simple path:  56%|█████▋    | 37354/66186 [00:57<01:06, 431.94it/s]

Simple path:  57%|█████▋    | 37409/66186 [00:57<01:02, 463.74it/s]

Simple path:  57%|█████▋    | 37461/66186 [00:58<01:00, 478.06it/s]

Simple path:  57%|█████▋    | 37510/66186 [00:58<00:59, 478.93it/s]

Simple path:  57%|█████▋    | 37559/66186 [00:58<01:03, 452.46it/s]

Simple path:  57%|█████▋    | 37605/66186 [00:58<01:03, 450.49it/s]

Simple path:  57%|█████▋    | 37651/66186 [00:58<01:02, 453.14it/s]

Simple path:  57%|█████▋    | 37699/66186 [00:58<01:01, 460.78it/s]

Simple path:  57%|█████▋    | 37746/66186 [00:58<01:01, 459.13it/s]

Simple path:  57%|█████▋    | 37793/66186 [00:58<01:01, 459.20it/s]

Simple path:  57%|█████▋    | 37840/66186 [00:58<01:02, 455.29it/s]

Simple path:  57%|█████▋    | 37886/66186 [00:59<01:02, 454.46it/s]

Simple path:  57%|█████▋    | 37932/66186 [00:59<01:03, 445.37it/s]

Simple path:  57%|█████▋    | 37977/66186 [00:59<01:03, 445.25it/s]

Simple path:  57%|█████▋    | 38025/66186 [00:59<01:02, 453.59it/s]

Simple path:  58%|█████▊    | 38072/66186 [00:59<01:01, 457.67it/s]

Simple path:  58%|█████▊    | 38118/66186 [00:59<01:01, 457.30it/s]

Simple path:  58%|█████▊    | 38165/66186 [00:59<01:00, 460.26it/s]

Simple path:  58%|█████▊    | 38212/66186 [00:59<01:00, 458.84it/s]

Simple path:  58%|█████▊    | 38258/66186 [00:59<01:01, 455.75it/s]

Simple path:  58%|█████▊    | 38304/66186 [01:00<01:19, 350.11it/s]

Simple path:  58%|█████▊    | 38347/66186 [01:00<01:15, 369.23it/s]

Simple path:  58%|█████▊    | 38389/66186 [01:00<01:12, 382.21it/s]

Simple path:  58%|█████▊    | 38433/66186 [01:00<01:10, 395.54it/s]

Simple path:  58%|█████▊    | 38489/66186 [01:00<01:02, 440.45it/s]

Simple path:  58%|█████▊    | 38544/66186 [01:00<00:58, 471.41it/s]

Simple path:  58%|█████▊    | 38600/66186 [01:00<00:55, 494.92it/s]

Simple path:  58%|█████▊    | 38657/66186 [01:00<00:53, 516.36it/s]

Simple path:  58%|█████▊    | 38710/66186 [01:00<00:53, 517.18it/s]

Simple path:  59%|█████▊    | 38766/66186 [01:00<00:51, 528.22it/s]

Simple path:  59%|█████▊    | 38821/66186 [01:01<00:51, 534.22it/s]

Simple path:  59%|█████▊    | 38875/66186 [01:01<00:53, 511.50it/s]

Simple path:  59%|█████▉    | 38927/66186 [01:01<00:53, 510.40it/s]

Simple path:  59%|█████▉    | 38979/66186 [01:01<00:53, 505.58it/s]

Simple path:  59%|█████▉    | 39030/66186 [01:01<00:55, 489.74it/s]

Simple path:  59%|█████▉    | 39080/66186 [01:01<00:56, 476.61it/s]

Simple path:  59%|█████▉    | 39128/66186 [01:01<00:58, 466.22it/s]

Simple path:  59%|█████▉    | 39175/66186 [01:01<01:12, 374.40it/s]

Simple path:  59%|█████▉    | 39218/66186 [01:01<01:09, 386.31it/s]

Simple path:  59%|█████▉    | 39260/66186 [01:02<01:08, 393.67it/s]

Simple path:  59%|█████▉    | 39304/66186 [01:02<01:06, 403.91it/s]

Simple path:  59%|█████▉    | 39347/66186 [01:02<01:05, 410.66it/s]

Simple path:  60%|█████▉    | 39390/66186 [01:02<01:04, 413.94it/s]

Simple path:  60%|█████▉    | 39434/66186 [01:02<01:03, 419.21it/s]

Simple path:  60%|█████▉    | 39478/66186 [01:02<01:03, 423.21it/s]

Simple path:  60%|█████▉    | 39521/66186 [01:02<01:02, 423.85it/s]

Simple path:  60%|█████▉    | 39564/66186 [01:02<01:03, 419.95it/s]

Simple path:  60%|█████▉    | 39607/66186 [01:02<01:04, 414.61it/s]

Simple path:  60%|█████▉    | 39649/66186 [01:03<01:04, 414.07it/s]

Simple path:  60%|█████▉    | 39691/66186 [01:03<01:04, 412.38it/s]

Simple path:  60%|██████    | 39733/66186 [01:03<01:04, 410.23it/s]

Simple path:  60%|██████    | 39775/66186 [01:03<01:04, 407.67it/s]

Simple path:  60%|██████    | 39816/66186 [01:03<01:04, 405.84it/s]

Simple path:  60%|██████    | 39857/66186 [01:03<01:05, 403.91it/s]

Simple path:  60%|██████    | 39898/66186 [01:03<01:04, 405.66it/s]

Simple path:  60%|██████    | 39939/66186 [01:03<01:04, 404.69it/s]

Simple path:  60%|██████    | 39980/66186 [01:03<01:05, 399.22it/s]

Simple path:  60%|██████    | 40034/66186 [01:03<00:59, 439.85it/s]

Simple path:  61%|██████    | 40091/66186 [01:04<00:54, 477.68it/s]

Simple path:  61%|██████    | 40148/66186 [01:04<00:51, 502.23it/s]

Simple path:  61%|██████    | 40205/66186 [01:04<00:49, 521.34it/s]

Simple path:  61%|██████    | 40262/66186 [01:04<00:48, 534.96it/s]

Simple path:  61%|██████    | 40319/66186 [01:04<00:47, 545.30it/s]

Simple path:  61%|██████    | 40377/66186 [01:04<00:46, 554.88it/s]

Simple path:  61%|██████    | 40434/66186 [01:04<00:46, 558.02it/s]

Simple path:  61%|██████    | 40492/66186 [01:04<00:45, 563.09it/s]

Simple path:  61%|██████▏   | 40549/66186 [01:04<00:45, 557.33it/s]

Simple path:  61%|██████▏   | 40605/66186 [01:04<00:47, 535.27it/s]

Simple path:  61%|██████▏   | 40659/66186 [01:05<00:48, 526.94it/s]

Simple path:  62%|██████▏   | 40712/66186 [01:05<00:49, 515.06it/s]

Simple path:  62%|██████▏   | 40764/66186 [01:05<00:50, 507.96it/s]

Simple path:  62%|██████▏   | 40815/66186 [01:05<00:50, 504.23it/s]

Simple path:  62%|██████▏   | 40866/66186 [01:05<00:50, 501.33it/s]

Simple path:  62%|██████▏   | 40917/66186 [01:05<00:50, 501.17it/s]

Simple path:  62%|██████▏   | 40968/66186 [01:05<00:50, 498.61it/s]

Simple path:  62%|██████▏   | 41018/66186 [01:05<00:50, 498.32it/s]

Simple path:  62%|██████▏   | 41069/66186 [01:05<00:50, 498.04it/s]

Simple path:  62%|██████▏   | 41119/66186 [01:05<00:50, 495.47it/s]

Simple path:  62%|██████▏   | 41169/66186 [01:06<00:50, 492.12it/s]

Simple path:  62%|██████▏   | 41219/66186 [01:06<00:51, 482.04it/s]

Simple path:  62%|██████▏   | 41268/66186 [01:06<00:52, 478.87it/s]

Simple path:  62%|██████▏   | 41316/66186 [01:06<00:52, 474.36it/s]

Simple path:  62%|██████▏   | 41364/66186 [01:06<00:52, 473.31it/s]

Simple path:  63%|██████▎   | 41412/66186 [01:06<00:52, 468.68it/s]

Simple path:  63%|██████▎   | 41460/66186 [01:06<00:52, 469.55it/s]

Simple path:  63%|██████▎   | 41507/66186 [01:06<00:52, 468.43it/s]

Simple path:  63%|██████▎   | 41556/66186 [01:06<00:52, 471.31it/s]

Simple path:  63%|██████▎   | 41614/66186 [01:07<00:48, 501.96it/s]

Simple path:  63%|██████▎   | 41684/66186 [01:07<00:43, 559.79it/s]

Simple path:  63%|██████▎   | 41757/66186 [01:07<00:40, 609.93it/s]

Simple path:  63%|██████▎   | 41829/66186 [01:07<00:38, 640.44it/s]

Simple path:  63%|██████▎   | 41904/66186 [01:07<00:36, 671.91it/s]

Simple path:  63%|██████▎   | 41976/66186 [01:07<00:35, 686.11it/s]

Simple path:  64%|██████▎   | 42050/66186 [01:07<00:34, 699.60it/s]

Simple path:  64%|██████▎   | 42120/66186 [01:07<00:36, 666.67it/s]

Simple path:  64%|██████▎   | 42188/66186 [01:07<00:38, 620.93it/s]

Simple path:  64%|██████▍   | 42251/66186 [01:07<00:40, 590.17it/s]

Simple path:  64%|██████▍   | 42311/66186 [01:08<00:41, 578.90it/s]

Simple path:  64%|██████▍   | 42370/66186 [01:08<00:41, 570.65it/s]

Simple path:  64%|██████▍   | 42428/66186 [01:08<00:41, 566.38it/s]

Simple path:  64%|██████▍   | 42485/66186 [01:08<00:42, 560.14it/s]

Simple path:  64%|██████▍   | 42542/66186 [01:08<00:42, 556.82it/s]

Simple path:  64%|██████▍   | 42598/66186 [01:08<00:43, 544.90it/s]

Simple path:  64%|██████▍   | 42653/66186 [01:08<00:45, 522.31it/s]

Simple path:  65%|██████▍   | 42706/66186 [01:08<00:46, 504.08it/s]

Simple path:  65%|██████▍   | 42757/66186 [01:08<00:48, 482.97it/s]

Simple path:  65%|██████▍   | 42806/66186 [01:09<00:50, 462.60it/s]

Simple path:  65%|██████▍   | 42853/66186 [01:09<00:51, 454.84it/s]

Simple path:  65%|██████▍   | 42899/66186 [01:09<00:51, 450.99it/s]

Simple path:  65%|██████▍   | 42945/66186 [01:09<00:52, 444.85it/s]

Simple path:  65%|██████▍   | 42990/66186 [01:09<00:52, 443.91it/s]

Simple path:  65%|██████▌   | 43035/66186 [01:09<00:52, 438.83it/s]

Simple path:  65%|██████▌   | 43079/66186 [01:09<00:52, 436.83it/s]

Simple path:  65%|██████▌   | 43135/66186 [01:09<00:48, 471.98it/s]

Simple path:  65%|██████▌   | 43194/66186 [01:09<00:45, 505.67it/s]

Simple path:  65%|██████▌   | 43257/66186 [01:10<00:42, 541.19it/s]

Simple path:  65%|██████▌   | 43320/66186 [01:10<00:40, 567.41it/s]

Simple path:  66%|██████▌   | 43385/66186 [01:10<00:38, 589.75it/s]

Simple path:  66%|██████▌   | 43449/66186 [01:10<00:37, 602.87it/s]

Simple path:  66%|██████▌   | 43512/66186 [01:10<00:37, 608.49it/s]

Simple path:  66%|██████▌   | 43576/66186 [01:10<00:36, 617.09it/s]

Simple path:  66%|██████▌   | 43638/66186 [01:10<00:37, 608.52it/s]

Simple path:  66%|██████▌   | 43699/66186 [01:10<00:37, 603.63it/s]

Simple path:  66%|██████▌   | 43760/66186 [01:10<00:37, 598.64it/s]

Simple path:  66%|██████▌   | 43824/66186 [01:10<00:36, 608.48it/s]

Simple path:  66%|██████▋   | 43885/66186 [01:11<00:37, 602.64it/s]

Simple path:  66%|██████▋   | 43947/66186 [01:11<00:36, 605.52it/s]

Simple path:  66%|██████▋   | 44008/66186 [01:11<00:36, 605.04it/s]

Simple path:  67%|██████▋   | 44070/66186 [01:11<00:36, 607.60it/s]

Simple path:  67%|██████▋   | 44131/66186 [01:11<00:37, 590.26it/s]

Simple path:  67%|██████▋   | 44191/66186 [01:11<00:38, 575.64it/s]

Simple path:  67%|██████▋   | 44249/66186 [01:11<00:38, 565.67it/s]

Simple path:  67%|██████▋   | 44306/66186 [01:11<00:39, 558.29it/s]

Simple path:  67%|██████▋   | 44362/66186 [01:11<00:39, 553.79it/s]

Simple path:  67%|██████▋   | 44418/66186 [01:11<00:39, 547.84it/s]

Simple path:  67%|██████▋   | 44473/66186 [01:12<00:40, 539.45it/s]

Simple path:  67%|██████▋   | 44527/66186 [01:12<00:40, 538.02it/s]

Simple path:  67%|██████▋   | 44581/66186 [01:12<00:40, 535.09it/s]

Simple path:  67%|██████▋   | 44644/66186 [01:12<00:38, 560.43it/s]

Simple path:  68%|██████▊   | 44711/66186 [01:12<00:36, 590.44it/s]

Simple path:  68%|██████▊   | 44777/66186 [01:12<00:35, 609.19it/s]

Simple path:  68%|██████▊   | 44842/66186 [01:12<00:34, 618.91it/s]

Simple path:  68%|██████▊   | 44907/66186 [01:12<00:33, 627.05it/s]

Simple path:  68%|██████▊   | 44971/66186 [01:12<00:33, 630.21it/s]

Simple path:  68%|██████▊   | 45035/66186 [01:13<00:33, 632.42it/s]

Simple path:  68%|██████▊   | 45099/66186 [01:13<00:34, 610.01it/s]

Simple path:  68%|██████▊   | 45161/66186 [01:13<00:35, 586.95it/s]

Simple path:  68%|██████▊   | 45220/66186 [01:13<00:36, 578.45it/s]

Simple path:  68%|██████▊   | 45279/66186 [01:13<00:36, 576.92it/s]

Simple path:  68%|██████▊   | 45337/66186 [01:13<00:36, 574.49it/s]

Simple path:  69%|██████▊   | 45395/66186 [01:13<00:36, 571.33it/s]

Simple path:  69%|██████▊   | 45453/66186 [01:13<00:36, 567.29it/s]

Simple path:  69%|██████▉   | 45510/66186 [01:13<00:36, 567.42it/s]

Simple path:  69%|██████▉   | 45567/66186 [01:13<00:36, 563.61it/s]

Simple path:  69%|██████▉   | 45624/66186 [01:14<00:38, 539.35it/s]

Simple path:  69%|██████▉   | 45679/66186 [01:14<00:39, 521.38it/s]

Simple path:  69%|██████▉   | 45732/66186 [01:14<00:40, 507.50it/s]

Simple path:  69%|██████▉   | 45783/66186 [01:14<00:40, 498.06it/s]

Simple path:  69%|██████▉   | 45833/66186 [01:14<00:41, 487.94it/s]

Simple path:  69%|██████▉   | 45882/66186 [01:14<00:41, 485.15it/s]

Simple path:  69%|██████▉   | 45931/66186 [01:14<00:41, 484.90it/s]

Simple path:  69%|██████▉   | 45981/66186 [01:14<00:41, 487.08it/s]

Simple path:  70%|██████▉   | 46031/66186 [01:14<00:41, 489.34it/s]

Simple path:  70%|██████▉   | 46088/66186 [01:15<00:39, 512.40it/s]

Simple path:  70%|██████▉   | 46154/66186 [01:15<00:36, 554.67it/s]

Simple path:  70%|██████▉   | 46219/66186 [01:15<00:34, 580.82it/s]

Simple path:  70%|██████▉   | 46284/66186 [01:15<00:33, 598.68it/s]

Simple path:  70%|███████   | 46345/66186 [01:15<00:33, 599.32it/s]

Simple path:  70%|███████   | 46409/66186 [01:15<00:32, 609.08it/s]

Simple path:  70%|███████   | 46473/66186 [01:15<00:32, 615.69it/s]

Simple path:  70%|███████   | 46535/66186 [01:15<00:31, 615.22it/s]

Simple path:  70%|███████   | 46597/66186 [01:15<00:33, 588.30it/s]

Simple path:  70%|███████   | 46657/66186 [01:15<00:36, 541.85it/s]

Simple path:  71%|███████   | 46713/66186 [01:16<00:37, 516.59it/s]

Simple path:  71%|███████   | 46767/66186 [01:16<00:37, 521.02it/s]

Simple path:  71%|███████   | 46820/66186 [01:16<00:37, 520.94it/s]

Simple path:  71%|███████   | 46874/66186 [01:16<00:36, 526.09it/s]

Simple path:  71%|███████   | 46928/66186 [01:16<00:36, 528.12it/s]

Simple path:  71%|███████   | 46983/66186 [01:16<00:36, 532.31it/s]

Simple path:  71%|███████   | 47037/66186 [01:16<00:36, 524.65it/s]

Simple path:  71%|███████   | 47090/66186 [01:16<00:37, 509.62it/s]

Simple path:  71%|███████   | 47142/66186 [01:16<00:38, 495.64it/s]

Simple path:  71%|███████▏  | 47192/66186 [01:17<00:39, 485.07it/s]

Simple path:  71%|███████▏  | 47241/66186 [01:17<00:39, 479.24it/s]

Simple path:  71%|███████▏  | 47289/66186 [01:17<00:39, 475.13it/s]

Simple path:  72%|███████▏  | 47337/66186 [01:17<00:39, 472.09it/s]

Simple path:  72%|███████▏  | 47385/66186 [01:17<00:39, 471.68it/s]

Simple path:  72%|███████▏  | 47433/66186 [01:17<00:39, 471.15it/s]

Simple path:  72%|███████▏  | 47481/66186 [01:17<00:39, 472.53it/s]

Simple path:  72%|███████▏  | 47529/66186 [01:17<00:40, 462.50it/s]

Simple path:  72%|███████▏  | 47576/66186 [01:17<00:41, 447.36it/s]

Simple path:  72%|███████▏  | 47621/66186 [01:17<00:43, 430.95it/s]

Simple path:  72%|███████▏  | 47665/66186 [01:18<00:44, 420.36it/s]

Simple path:  72%|███████▏  | 47708/66186 [01:18<00:45, 408.24it/s]

Simple path:  72%|███████▏  | 47749/66186 [01:18<00:45, 403.69it/s]

Simple path:  72%|███████▏  | 47790/66186 [01:18<00:45, 402.09it/s]

Simple path:  72%|███████▏  | 47831/66186 [01:18<00:46, 398.12it/s]

Simple path:  72%|███████▏  | 47871/66186 [01:18<00:45, 398.36it/s]

Simple path:  72%|███████▏  | 47911/66186 [01:18<00:45, 397.30it/s]

Simple path:  72%|███████▏  | 47951/66186 [01:18<00:45, 396.51it/s]

Simple path:  73%|███████▎  | 47991/66186 [01:18<00:46, 394.39it/s]

Simple path:  73%|███████▎  | 48031/66186 [01:19<00:46, 392.47it/s]

Simple path:  73%|███████▎  | 48072/66186 [01:19<00:45, 395.94it/s]

Simple path:  73%|███████▎  | 48112/66186 [01:19<00:46, 391.51it/s]

Simple path:  73%|███████▎  | 48152/66186 [01:19<00:46, 387.83it/s]

Simple path:  73%|███████▎  | 48191/66186 [01:19<00:46, 383.88it/s]

Simple path:  73%|███████▎  | 48230/66186 [01:19<00:47, 380.08it/s]

Simple path:  73%|███████▎  | 48269/66186 [01:19<00:46, 382.80it/s]

Simple path:  73%|███████▎  | 48309/66186 [01:19<00:46, 387.54it/s]

Simple path:  73%|███████▎  | 48348/66186 [01:19<00:46, 385.96it/s]

Simple path:  73%|███████▎  | 48387/66186 [01:19<00:46, 384.47it/s]

Simple path:  73%|███████▎  | 48428/66186 [01:20<00:45, 390.29it/s]

Simple path:  73%|███████▎  | 48470/66186 [01:20<00:44, 398.09it/s]

Simple path:  73%|███████▎  | 48510/66186 [01:20<00:44, 396.77it/s]

Simple path:  73%|███████▎  | 48550/66186 [01:20<00:44, 394.66it/s]

Simple path:  73%|███████▎  | 48590/66186 [01:20<00:44, 392.67it/s]

Simple path:  73%|███████▎  | 48630/66186 [01:20<00:44, 391.17it/s]

Simple path:  74%|███████▎  | 48670/66186 [01:20<00:45, 388.65it/s]

Simple path:  74%|███████▎  | 48709/66186 [01:20<00:45, 388.38it/s]

Simple path:  74%|███████▎  | 48748/66186 [01:20<00:45, 386.03it/s]

Simple path:  74%|███████▎  | 48787/66186 [01:20<00:45, 385.04it/s]

Simple path:  74%|███████▍  | 48826/66186 [01:21<00:45, 384.24it/s]

Simple path:  74%|███████▍  | 48865/66186 [01:21<00:44, 385.42it/s]

Simple path:  74%|███████▍  | 48905/66186 [01:21<00:44, 387.10it/s]

Simple path:  74%|███████▍  | 48946/66186 [01:21<00:43, 392.52it/s]

Simple path:  74%|███████▍  | 48988/66186 [01:21<00:42, 400.29it/s]

Simple path:  74%|███████▍  | 49029/66186 [01:21<00:43, 394.48it/s]

Simple path:  74%|███████▍  | 49070/66186 [01:21<00:42, 398.63it/s]

Simple path:  74%|███████▍  | 49110/66186 [01:21<00:43, 394.79it/s]

Simple path:  74%|███████▍  | 49150/66186 [01:21<00:43, 392.39it/s]

Simple path:  74%|███████▍  | 49190/66186 [01:22<00:43, 388.78it/s]

Simple path:  74%|███████▍  | 49229/66186 [01:22<00:44, 384.79it/s]

Simple path:  74%|███████▍  | 49268/66186 [01:22<00:44, 383.11it/s]

Simple path:  74%|███████▍  | 49307/66186 [01:22<00:43, 385.11it/s]

Simple path:  75%|███████▍  | 49346/66186 [01:22<00:43, 384.45it/s]

Simple path:  75%|███████▍  | 49385/66186 [01:22<00:43, 382.11it/s]

Simple path:  75%|███████▍  | 49426/66186 [01:22<00:43, 388.42it/s]

Simple path:  75%|███████▍  | 49466/66186 [01:22<00:42, 390.30it/s]

Simple path:  75%|███████▍  | 49506/66186 [01:22<00:43, 385.42it/s]

Simple path:  75%|███████▍  | 49545/66186 [01:22<00:43, 385.53it/s]

Simple path:  75%|███████▍  | 49584/66186 [01:23<00:43, 381.17it/s]

Simple path:  75%|███████▍  | 49623/66186 [01:23<00:43, 381.64it/s]

Simple path:  75%|███████▌  | 49662/66186 [01:23<00:43, 382.33it/s]

Simple path:  75%|███████▌  | 49701/66186 [01:23<00:43, 379.43it/s]

Simple path:  75%|███████▌  | 49740/66186 [01:23<00:43, 379.72it/s]

Simple path:  75%|███████▌  | 49780/66186 [01:23<00:42, 384.00it/s]

Simple path:  75%|███████▌  | 49819/66186 [01:23<00:42, 384.41it/s]

Simple path:  75%|███████▌  | 49858/66186 [01:23<00:42, 384.02it/s]

Simple path:  75%|███████▌  | 49898/66186 [01:23<00:42, 385.78it/s]

Simple path:  75%|███████▌  | 49938/66186 [01:23<00:41, 388.42it/s]

Simple path:  76%|███████▌  | 49977/66186 [01:24<00:41, 387.52it/s]

Simple path:  76%|███████▌  | 50017/66186 [01:24<00:41, 389.67it/s]

Simple path:  76%|███████▌  | 50057/66186 [01:24<00:41, 390.41it/s]

Simple path:  76%|███████▌  | 50097/66186 [01:24<00:41, 388.61it/s]

Simple path:  76%|███████▌  | 50136/66186 [01:24<00:41, 387.91it/s]

Simple path:  76%|███████▌  | 50176/66186 [01:24<00:41, 390.23it/s]

Simple path:  76%|███████▌  | 50216/66186 [01:24<00:41, 386.46it/s]

Simple path:  76%|███████▌  | 50255/66186 [01:24<00:41, 383.99it/s]

Simple path:  76%|███████▌  | 50296/66186 [01:24<00:40, 388.89it/s]

Simple path:  76%|███████▌  | 50336/66186 [01:24<00:40, 390.10it/s]

Simple path:  76%|███████▌  | 50376/66186 [01:25<00:40, 387.16it/s]

Simple path:  76%|███████▌  | 50415/66186 [01:25<00:40, 386.87it/s]

Simple path:  76%|███████▌  | 50455/66186 [01:25<00:40, 389.52it/s]

Simple path:  76%|███████▋  | 50495/66186 [01:25<00:40, 390.47it/s]

Simple path:  76%|███████▋  | 50535/66186 [01:25<00:40, 385.17it/s]

Simple path:  76%|███████▋  | 50574/66186 [01:25<00:43, 360.64it/s]

Simple path:  76%|███████▋  | 50613/66186 [01:25<00:42, 366.50it/s]

Simple path:  77%|███████▋  | 50650/66186 [01:25<00:43, 361.19it/s]

Simple path:  77%|███████▋  | 50688/66186 [01:25<00:42, 365.44it/s]

Simple path:  77%|███████▋  | 50726/66186 [01:26<00:42, 367.49it/s]

Simple path:  77%|███████▋  | 50764/66186 [01:26<00:41, 370.56it/s]

Simple path:  77%|███████▋  | 50803/66186 [01:26<00:41, 374.58it/s]

Simple path:  77%|███████▋  | 50841/66186 [01:26<00:40, 374.42it/s]

Simple path:  77%|███████▋  | 50881/66186 [01:26<00:40, 379.20it/s]

Simple path:  77%|███████▋  | 50921/66186 [01:26<00:39, 382.85it/s]

Simple path:  77%|███████▋  | 50960/66186 [01:26<00:39, 384.74it/s]

Simple path:  77%|███████▋  | 50999/66186 [01:26<00:39, 383.95it/s]

Simple path:  77%|███████▋  | 51038/66186 [01:26<00:39, 381.67it/s]

Simple path:  77%|███████▋  | 51077/66186 [01:26<00:39, 379.88it/s]

Simple path:  77%|███████▋  | 51115/66186 [01:27<00:39, 378.91it/s]

Simple path:  77%|███████▋  | 51154/66186 [01:27<00:39, 381.79it/s]

Simple path:  77%|███████▋  | 51193/66186 [01:27<00:39, 383.46it/s]

Simple path:  77%|███████▋  | 51232/66186 [01:27<00:39, 381.08it/s]

Simple path:  77%|███████▋  | 51271/66186 [01:27<00:38, 382.79it/s]

Simple path:  78%|███████▊  | 51311/66186 [01:27<00:38, 386.69it/s]

Simple path:  78%|███████▊  | 51354/66186 [01:27<00:37, 398.48it/s]

Simple path:  78%|███████▊  | 51397/66186 [01:27<00:36, 405.81it/s]

Simple path:  78%|███████▊  | 51439/66186 [01:27<00:36, 408.66it/s]

Simple path:  78%|███████▊  | 51481/66186 [01:27<00:35, 409.02it/s]

Simple path:  78%|███████▊  | 51522/66186 [01:28<00:36, 406.45it/s]

Simple path:  78%|███████▊  | 51563/66186 [01:28<00:36, 403.54it/s]

Simple path:  78%|███████▊  | 51604/66186 [01:28<00:36, 400.35it/s]

Simple path:  78%|███████▊  | 51645/66186 [01:28<00:36, 396.44it/s]

Simple path:  78%|███████▊  | 51685/66186 [01:28<00:36, 395.30it/s]

Simple path:  78%|███████▊  | 51725/66186 [01:28<00:36, 395.23it/s]

Simple path:  78%|███████▊  | 51765/66186 [01:28<00:36, 394.83it/s]

Simple path:  78%|███████▊  | 51805/66186 [01:28<00:36, 393.28it/s]

Simple path:  78%|███████▊  | 51846/66186 [01:28<00:36, 395.47it/s]

Simple path:  78%|███████▊  | 51888/66186 [01:28<00:35, 400.46it/s]

Simple path:  78%|███████▊  | 51931/66186 [01:29<00:35, 406.59it/s]

Simple path:  79%|███████▊  | 51973/66186 [01:29<00:34, 408.63it/s]

Simple path:  79%|███████▊  | 52015/66186 [01:29<00:34, 409.76it/s]

Simple path:  79%|███████▊  | 52057/66186 [01:29<00:34, 410.22it/s]

Simple path:  79%|███████▊  | 52099/66186 [01:29<00:34, 403.65it/s]

Simple path:  79%|███████▉  | 52140/66186 [01:29<00:34, 404.58it/s]

Simple path:  79%|███████▉  | 52181/66186 [01:29<00:34, 403.99it/s]

Simple path:  79%|███████▉  | 52222/66186 [01:29<00:34, 403.82it/s]

Simple path:  79%|███████▉  | 52263/66186 [01:29<00:34, 404.29it/s]

Simple path:  79%|███████▉  | 52304/66186 [01:30<00:34, 401.98it/s]

Simple path:  79%|███████▉  | 52345/66186 [01:30<00:34, 401.03it/s]

Simple path:  79%|███████▉  | 52387/66186 [01:30<00:34, 405.02it/s]

Simple path:  79%|███████▉  | 52430/66186 [01:30<00:33, 409.82it/s]

Simple path:  79%|███████▉  | 52473/66186 [01:30<00:33, 413.00it/s]

Simple path:  79%|███████▉  | 52515/66186 [01:30<00:33, 411.96it/s]

Simple path:  79%|███████▉  | 52557/66186 [01:30<00:33, 412.01it/s]

Simple path:  79%|███████▉  | 52599/66186 [01:30<00:33, 408.81it/s]

Simple path:  80%|███████▉  | 52640/66186 [01:30<00:33, 407.11it/s]

Simple path:  80%|███████▉  | 52681/66186 [01:30<00:33, 405.46it/s]

Simple path:  80%|███████▉  | 52722/66186 [01:31<00:33, 404.06it/s]

Simple path:  80%|███████▉  | 52763/66186 [01:31<00:33, 402.42it/s]

Simple path:  80%|███████▉  | 52805/66186 [01:31<00:32, 406.24it/s]

Simple path:  80%|███████▉  | 52846/66186 [01:31<00:32, 405.61it/s]

Simple path:  80%|███████▉  | 52887/66186 [01:31<00:32, 404.14it/s]

Simple path:  80%|███████▉  | 52928/66186 [01:31<00:32, 403.87it/s]

Simple path:  80%|████████  | 52970/66186 [01:31<00:32, 405.93it/s]

Simple path:  80%|████████  | 53011/66186 [01:31<00:32, 405.08it/s]

Simple path:  80%|████████  | 53052/66186 [01:31<00:32, 405.05it/s]

Simple path:  80%|████████  | 53093/66186 [01:31<00:32, 402.10it/s]

Simple path:  80%|████████  | 53134/66186 [01:32<00:32, 399.49it/s]

Simple path:  80%|████████  | 53175/66186 [01:32<00:32, 399.84it/s]

Simple path:  80%|████████  | 53215/66186 [01:32<00:32, 399.31it/s]

Simple path:  80%|████████  | 53255/66186 [01:32<00:32, 399.00it/s]

Simple path:  81%|████████  | 53296/66186 [01:32<00:32, 400.40it/s]

Simple path:  81%|████████  | 53337/66186 [01:32<00:32, 399.88it/s]

Simple path:  81%|████████  | 53377/66186 [01:32<00:32, 397.97it/s]

Simple path:  81%|████████  | 53418/66186 [01:32<00:31, 399.75it/s]

Simple path:  81%|████████  | 53458/66186 [01:32<00:31, 399.30it/s]

Simple path:  81%|████████  | 53501/66186 [01:32<00:31, 405.37it/s]

Simple path:  81%|████████  | 53542/66186 [01:33<00:31, 406.48it/s]

Simple path:  81%|████████  | 53583/66186 [01:33<00:31, 402.67it/s]

Simple path:  81%|████████  | 53624/66186 [01:33<00:31, 400.89it/s]

Simple path:  81%|████████  | 53665/66186 [01:33<00:31, 397.39it/s]

Simple path:  81%|████████  | 53705/66186 [01:33<00:31, 396.11it/s]

Simple path:  81%|████████  | 53745/66186 [01:33<00:31, 396.34it/s]

Simple path:  81%|████████▏ | 53785/66186 [01:33<00:31, 395.91it/s]

Simple path:  81%|████████▏ | 53825/66186 [01:33<00:31, 396.67it/s]

Simple path:  81%|████████▏ | 53866/66186 [01:33<00:30, 397.77it/s]

Simple path:  81%|████████▏ | 53906/66186 [01:33<00:30, 397.66it/s]

Simple path:  82%|████████▏ | 53946/66186 [01:34<00:30, 397.51it/s]

Simple path:  82%|████████▏ | 53987/66186 [01:34<00:30, 400.20it/s]

Simple path:  82%|████████▏ | 54029/66186 [01:34<00:30, 402.67it/s]

Simple path:  82%|████████▏ | 54070/66186 [01:34<00:30, 399.06it/s]

Simple path:  82%|████████▏ | 54110/66186 [01:34<00:33, 362.77it/s]

Simple path:  82%|████████▏ | 54148/66186 [01:34<00:32, 365.52it/s]

Simple path:  82%|████████▏ | 54185/66186 [01:34<00:32, 366.47it/s]

Simple path:  82%|████████▏ | 54223/66186 [01:34<00:32, 370.35it/s]

Simple path:  82%|████████▏ | 54261/66186 [01:34<00:32, 372.45it/s]

Simple path:  82%|████████▏ | 54299/66186 [01:35<00:31, 373.34it/s]

Simple path:  82%|████████▏ | 54337/66186 [01:35<00:31, 375.02it/s]

Simple path:  82%|████████▏ | 54375/66186 [01:35<00:31, 374.35it/s]

Simple path:  82%|████████▏ | 54413/66186 [01:35<00:31, 374.98it/s]

Simple path:  82%|████████▏ | 54452/66186 [01:35<00:31, 376.97it/s]

Simple path:  82%|████████▏ | 54491/66186 [01:35<00:30, 379.40it/s]

Simple path:  82%|████████▏ | 54532/66186 [01:35<00:30, 386.71it/s]

Simple path:  82%|████████▏ | 54575/66186 [01:35<00:29, 399.10it/s]

Simple path:  83%|████████▎ | 54619/66186 [01:35<00:28, 409.50it/s]

Simple path:  83%|████████▎ | 54662/66186 [01:35<00:27, 415.25it/s]

Simple path:  83%|████████▎ | 54705/66186 [01:36<00:27, 418.05it/s]

Simple path:  83%|████████▎ | 54747/66186 [01:36<00:27, 417.78it/s]

Simple path:  83%|████████▎ | 54790/66186 [01:36<00:27, 419.45it/s]

Simple path:  83%|████████▎ | 54832/66186 [01:36<00:27, 418.78it/s]

Simple path:  83%|████████▎ | 54875/66186 [01:36<00:26, 419.25it/s]

Simple path:  83%|████████▎ | 54917/66186 [01:36<00:26, 418.54it/s]

Simple path:  83%|████████▎ | 54959/66186 [01:36<00:27, 413.94it/s]

Simple path:  83%|████████▎ | 55002/66186 [01:36<00:26, 415.92it/s]

Simple path:  83%|████████▎ | 55044/66186 [01:36<00:26, 415.76it/s]

Simple path:  83%|████████▎ | 55088/66186 [01:36<00:26, 422.40it/s]

Simple path:  83%|████████▎ | 55131/66186 [01:37<00:26, 424.16it/s]

Simple path:  83%|████████▎ | 55174/66186 [01:37<00:26, 422.06it/s]

Simple path:  83%|████████▎ | 55217/66186 [01:37<00:26, 420.69it/s]

Simple path:  83%|████████▎ | 55260/66186 [01:37<00:26, 418.64it/s]

Simple path:  84%|████████▎ | 55302/66186 [01:37<00:26, 415.35it/s]

Simple path:  84%|████████▎ | 55344/66186 [01:37<00:26, 407.39it/s]

Simple path:  84%|████████▎ | 55385/66186 [01:37<00:26, 402.09it/s]

Simple path:  84%|████████▎ | 55426/66186 [01:37<00:26, 398.83it/s]

Simple path:  84%|████████▍ | 55466/66186 [01:37<00:27, 394.41it/s]

Simple path:  84%|████████▍ | 55506/66186 [01:38<00:27, 392.34it/s]

Simple path:  84%|████████▍ | 55548/66186 [01:38<00:26, 398.77it/s]

Simple path:  84%|████████▍ | 55592/66186 [01:38<00:25, 410.53it/s]

Simple path:  84%|████████▍ | 55636/66186 [01:38<00:25, 416.65it/s]

Simple path:  84%|████████▍ | 55679/66186 [01:38<00:24, 420.36it/s]

Simple path:  84%|████████▍ | 55722/66186 [01:38<00:24, 418.61it/s]

Simple path:  84%|████████▍ | 55764/66186 [01:38<00:24, 418.33it/s]

Simple path:  84%|████████▍ | 55806/66186 [01:38<00:24, 416.95it/s]

Simple path:  84%|████████▍ | 55848/66186 [01:38<00:24, 416.63it/s]

Simple path:  84%|████████▍ | 55890/66186 [01:38<00:24, 414.50it/s]

Simple path:  85%|████████▍ | 55932/66186 [01:39<00:24, 414.05it/s]

Simple path:  85%|████████▍ | 55974/66186 [01:39<00:24, 412.71it/s]

Simple path:  85%|████████▍ | 56016/66186 [01:39<00:24, 411.73it/s]

Simple path:  85%|████████▍ | 56064/66186 [01:39<00:23, 431.39it/s]

Simple path:  85%|████████▍ | 56112/66186 [01:39<00:22, 443.48it/s]

Simple path:  85%|████████▍ | 56158/66186 [01:39<00:22, 446.74it/s]

Simple path:  85%|████████▍ | 56205/66186 [01:39<00:22, 452.06it/s]

Simple path:  85%|████████▍ | 56252/66186 [01:39<00:21, 456.69it/s]

Simple path:  85%|████████▌ | 56298/66186 [01:39<00:21, 453.86it/s]

Simple path:  85%|████████▌ | 56344/66186 [01:39<00:21, 452.67it/s]

Simple path:  85%|████████▌ | 56390/66186 [01:40<00:21, 451.88it/s]

Simple path:  85%|████████▌ | 56436/66186 [01:40<00:21, 452.48it/s]

Simple path:  85%|████████▌ | 56483/66186 [01:40<00:21, 455.93it/s]

Simple path:  85%|████████▌ | 56532/66186 [01:40<00:20, 464.75it/s]

Simple path:  85%|████████▌ | 56580/66186 [01:40<00:20, 467.06it/s]

Simple path:  86%|████████▌ | 56628/66186 [01:40<00:20, 469.43it/s]

Simple path:  86%|████████▌ | 56676/66186 [01:40<00:20, 470.29it/s]

Simple path:  86%|████████▌ | 56724/66186 [01:40<00:20, 472.96it/s]

Simple path:  86%|████████▌ | 56772/66186 [01:40<00:19, 470.79it/s]

Simple path:  86%|████████▌ | 56823/66186 [01:40<00:19, 481.01it/s]

Simple path:  86%|████████▌ | 56872/66186 [01:41<00:19, 482.96it/s]

Simple path:  86%|████████▌ | 56921/66186 [01:41<00:19, 476.70it/s]

Simple path:  86%|████████▌ | 56969/66186 [01:41<00:20, 460.09it/s]

Simple path:  86%|████████▌ | 57016/66186 [01:41<00:20, 444.05it/s]

Simple path:  86%|████████▌ | 57061/66186 [01:41<00:20, 434.98it/s]

Simple path:  86%|████████▋ | 57105/66186 [01:41<00:21, 428.84it/s]

Simple path:  86%|████████▋ | 57148/66186 [01:41<00:21, 424.77it/s]

Simple path:  86%|████████▋ | 57191/66186 [01:41<00:21, 425.00it/s]

Simple path:  86%|████████▋ | 57234/66186 [01:41<00:21, 422.40it/s]

Simple path:  87%|████████▋ | 57277/66186 [01:42<00:21, 422.09it/s]

Simple path:  87%|████████▋ | 57320/66186 [01:42<00:21, 421.06it/s]

Simple path:  87%|████████▋ | 57363/66186 [01:42<00:20, 422.32it/s]

Simple path:  87%|████████▋ | 57427/66186 [01:42<00:18, 484.53it/s]

Simple path:  87%|████████▋ | 57494/66186 [01:42<00:16, 538.40it/s]

Simple path:  87%|████████▋ | 57560/66186 [01:42<00:15, 573.73it/s]

Simple path:  87%|████████▋ | 57625/66186 [01:42<00:14, 594.00it/s]

Simple path:  87%|████████▋ | 57690/66186 [01:42<00:13, 607.98it/s]

Simple path:  87%|████████▋ | 57756/66186 [01:42<00:13, 621.80it/s]

Simple path:  87%|████████▋ | 57821/66186 [01:42<00:13, 628.31it/s]

Simple path:  87%|████████▋ | 57887/66186 [01:43<00:13, 634.80it/s]

Simple path:  88%|████████▊ | 57952/66186 [01:43<00:12, 638.64it/s]

Simple path:  88%|████████▊ | 58018/66186 [01:43<00:12, 641.71it/s]

Simple path:  88%|████████▊ | 58084/66186 [01:43<00:12, 645.47it/s]

Simple path:  88%|████████▊ | 58150/66186 [01:43<00:12, 648.18it/s]

Simple path:  88%|████████▊ | 58216/66186 [01:43<00:12, 648.45it/s]

Simple path:  88%|████████▊ | 58283/66186 [01:43<00:12, 653.36it/s]

Simple path:  88%|████████▊ | 58349/66186 [01:43<00:12, 652.81it/s]

Simple path:  88%|████████▊ | 58416/66186 [01:43<00:11, 655.02it/s]

Simple path:  88%|████████▊ | 58483/66186 [01:43<00:11, 657.15it/s]

Simple path:  88%|████████▊ | 58550/66186 [01:44<00:11, 660.57it/s]

Simple path:  89%|████████▊ | 58617/66186 [01:44<00:11, 658.11it/s]

Simple path:  89%|████████▊ | 58683/66186 [01:44<00:11, 655.68it/s]

Simple path:  89%|████████▉ | 58749/66186 [01:44<00:11, 656.27it/s]

Simple path:  89%|████████▉ | 58815/66186 [01:44<00:11, 652.84it/s]

Simple path:  89%|████████▉ | 58881/66186 [01:44<00:11, 648.90it/s]

Simple path:  89%|████████▉ | 58946/66186 [01:44<00:11, 647.20it/s]

Simple path:  89%|████████▉ | 59012/66186 [01:44<00:11, 648.87it/s]

Simple path:  89%|████████▉ | 59078/66186 [01:44<00:10, 651.67it/s]

Simple path:  89%|████████▉ | 59145/66186 [01:44<00:10, 655.66it/s]

Simple path:  89%|████████▉ | 59211/66186 [01:45<00:10, 655.23it/s]

Simple path:  90%|████████▉ | 59277/66186 [01:45<00:10, 655.81it/s]

Simple path:  90%|████████▉ | 59343/66186 [01:45<00:10, 650.78it/s]

Simple path:  90%|████████▉ | 59411/66186 [01:45<00:10, 656.71it/s]

Simple path:  90%|████████▉ | 59478/66186 [01:45<00:10, 658.57it/s]

Simple path:  90%|████████▉ | 59544/66186 [01:45<00:10, 657.03it/s]

Simple path:  90%|█████████ | 59610/66186 [01:45<00:10, 655.22it/s]

Simple path:  90%|█████████ | 59676/66186 [01:45<00:09, 652.85it/s]

Simple path:  90%|█████████ | 59742/66186 [01:45<00:10, 625.36it/s]

Simple path:  90%|█████████ | 59805/66186 [01:46<00:12, 494.75it/s]

Simple path:  90%|█████████ | 59859/66186 [01:46<00:14, 438.06it/s]

Simple path:  91%|█████████ | 59907/66186 [01:46<00:15, 409.39it/s]

Simple path:  91%|█████████ | 59951/66186 [01:46<00:16, 379.82it/s]

Simple path:  91%|█████████ | 59991/66186 [01:46<00:17, 355.83it/s]

Simple path:  91%|█████████ | 60028/66186 [01:46<00:17, 347.89it/s]

Simple path:  91%|█████████ | 60064/66186 [01:46<00:18, 334.18it/s]

Simple path:  91%|█████████ | 60099/66186 [01:46<00:18, 337.63it/s]

Simple path:  91%|█████████ | 60134/66186 [01:47<00:18, 331.58it/s]

Simple path:  91%|█████████ | 60168/66186 [01:47<00:18, 329.75it/s]

Simple path:  91%|█████████ | 60202/66186 [01:47<00:18, 322.01it/s]

Simple path:  91%|█████████ | 60236/66186 [01:47<00:18, 325.77it/s]

Simple path:  91%|█████████ | 60271/66186 [01:47<00:17, 330.30it/s]

Simple path:  91%|█████████ | 60306/66186 [01:47<00:17, 332.13it/s]

Simple path:  91%|█████████ | 60340/66186 [01:47<00:17, 327.82it/s]

Simple path:  91%|█████████ | 60373/66186 [01:47<00:18, 322.88it/s]

Simple path:  91%|█████████▏| 60407/66186 [01:47<00:17, 325.31it/s]

Simple path:  91%|█████████▏| 60441/66186 [01:48<00:17, 328.36it/s]

Simple path:  91%|█████████▏| 60474/66186 [01:48<00:17, 326.98it/s]

Simple path:  91%|█████████▏| 60507/66186 [01:48<00:19, 292.50it/s]

Simple path:  91%|█████████▏| 60541/66186 [01:48<00:18, 305.18it/s]

Simple path:  92%|█████████▏| 60578/66186 [01:48<00:17, 322.83it/s]

Simple path:  92%|█████████▏| 60611/66186 [01:48<00:17, 324.68it/s]

Simple path:  92%|█████████▏| 60644/66186 [01:48<00:17, 317.91it/s]

Simple path:  92%|█████████▏| 60678/66186 [01:48<00:17, 321.40it/s]

Simple path:  92%|█████████▏| 60711/66186 [01:48<00:17, 313.79it/s]

Simple path:  92%|█████████▏| 60745/66186 [01:49<00:17, 319.99it/s]

Simple path:  92%|█████████▏| 60779/66186 [01:49<00:16, 321.87it/s]

Simple path:  92%|█████████▏| 60814/66186 [01:49<00:16, 328.35it/s]

Simple path:  92%|█████████▏| 60851/66186 [01:49<00:15, 335.32it/s]

Simple path:  92%|█████████▏| 60885/66186 [01:49<00:16, 329.43it/s]

Simple path:  92%|█████████▏| 60920/66186 [01:49<00:15, 334.64it/s]

Simple path:  92%|█████████▏| 60955/66186 [01:49<00:15, 336.94it/s]

Simple path:  92%|█████████▏| 60989/66186 [01:49<00:15, 337.21it/s]

Simple path:  92%|█████████▏| 61023/66186 [01:49<00:15, 335.62it/s]

Simple path:  92%|█████████▏| 61058/66186 [01:49<00:15, 339.51it/s]

Simple path:  92%|█████████▏| 61092/66186 [01:50<00:15, 329.38it/s]

Simple path:  92%|█████████▏| 61130/66186 [01:50<00:14, 341.95it/s]

Simple path:  92%|█████████▏| 61165/66186 [01:50<00:15, 334.63it/s]

Simple path:  92%|█████████▏| 61200/66186 [01:50<00:14, 338.57it/s]

Simple path:  93%|█████████▎| 61234/66186 [01:50<00:14, 337.15it/s]

Simple path:  93%|█████████▎| 61268/66186 [01:50<00:14, 329.11it/s]

Simple path:  93%|█████████▎| 61302/66186 [01:50<00:14, 331.61it/s]

Simple path:  93%|█████████▎| 61336/66186 [01:50<00:14, 331.44it/s]

Simple path:  93%|█████████▎| 61370/66186 [01:50<00:14, 331.94it/s]

Simple path:  93%|█████████▎| 61404/66186 [01:50<00:14, 332.01it/s]

Simple path:  93%|█████████▎| 61438/66186 [01:51<00:14, 331.94it/s]

Simple path:  93%|█████████▎| 61473/66186 [01:51<00:14, 333.77it/s]

Simple path:  93%|█████████▎| 61510/66186 [01:51<00:13, 342.15it/s]

Simple path:  93%|█████████▎| 61545/66186 [01:51<00:13, 334.03it/s]

Simple path:  93%|█████████▎| 61580/66186 [01:51<00:13, 337.43it/s]

Simple path:  93%|█████████▎| 61615/66186 [01:51<00:13, 339.49it/s]

Simple path:  93%|█████████▎| 61649/66186 [01:51<00:13, 339.20it/s]

Simple path:  93%|█████████▎| 61683/66186 [01:51<00:13, 327.52it/s]

Simple path:  93%|█████████▎| 61719/66186 [01:51<00:13, 334.83it/s]

Simple path:  93%|█████████▎| 61754/66186 [01:52<00:13, 337.30it/s]

Simple path:  93%|█████████▎| 61788/66186 [01:52<00:14, 307.41it/s]

Simple path:  93%|█████████▎| 61823/66186 [01:52<00:13, 318.41it/s]

Simple path:  93%|█████████▎| 61856/66186 [01:52<00:13, 320.97it/s]

Simple path:  94%|█████████▎| 61889/66186 [01:52<00:15, 280.96it/s]

Simple path:  94%|█████████▎| 61920/66186 [01:52<00:14, 287.65it/s]

Simple path:  94%|█████████▎| 61950/66186 [01:52<00:14, 283.53it/s]

Simple path:  94%|█████████▎| 61981/66186 [01:52<00:14, 289.11it/s]

Simple path:  94%|█████████▎| 62011/66186 [01:52<00:14, 285.32it/s]

Simple path:  94%|█████████▎| 62042/66186 [01:53<00:14, 289.74it/s]

Simple path:  94%|█████████▍| 62073/66186 [01:53<00:14, 292.85it/s]

Simple path:  94%|█████████▍| 62104/66186 [01:53<00:13, 296.75it/s]

Simple path:  94%|█████████▍| 62134/66186 [01:53<00:13, 290.68it/s]

Simple path:  94%|█████████▍| 62165/66186 [01:53<00:13, 294.44it/s]

Simple path:  94%|█████████▍| 62195/66186 [01:53<00:13, 291.70it/s]

Simple path:  94%|█████████▍| 62225/66186 [01:53<00:13, 294.03it/s]

Simple path:  94%|█████████▍| 62255/66186 [01:53<00:13, 293.34it/s]

Simple path:  94%|█████████▍| 62287/66186 [01:53<00:13, 299.49it/s]

Simple path:  94%|█████████▍| 62319/66186 [01:53<00:12, 303.57it/s]

Simple path:  94%|█████████▍| 62350/66186 [01:54<00:12, 302.11it/s]

Simple path:  94%|█████████▍| 62382/66186 [01:54<00:12, 305.07it/s]

Simple path:  94%|█████████▍| 62413/66186 [01:54<00:12, 298.98it/s]

Simple path:  94%|█████████▍| 62444/66186 [01:54<00:12, 301.21it/s]

Simple path:  94%|█████████▍| 62475/66186 [01:54<00:12, 301.94it/s]

Simple path:  94%|█████████▍| 62508/66186 [01:54<00:12, 306.33it/s]

Simple path:  94%|█████████▍| 62540/66186 [01:54<00:11, 307.56it/s]

Simple path:  95%|█████████▍| 62571/66186 [01:54<00:11, 307.22it/s]

Simple path:  95%|█████████▍| 62602/66186 [01:54<00:12, 298.27it/s]

Simple path:  95%|█████████▍| 62632/66186 [01:54<00:11, 298.37it/s]

Simple path:  95%|█████████▍| 62664/66186 [01:55<00:11, 304.13it/s]

Simple path:  95%|█████████▍| 62695/66186 [01:55<00:11, 298.75it/s]

Simple path:  95%|█████████▍| 62725/66186 [01:55<00:11, 298.96it/s]

Simple path:  95%|█████████▍| 62755/66186 [01:55<00:11, 296.26it/s]

Simple path:  95%|█████████▍| 62788/66186 [01:55<00:11, 303.86it/s]

Simple path:  95%|█████████▍| 62820/66186 [01:55<00:11, 305.10it/s]

Simple path:  95%|█████████▍| 62852/66186 [01:55<00:10, 309.18it/s]

Simple path:  95%|█████████▌| 62883/66186 [01:55<00:10, 308.07it/s]

Simple path:  95%|█████████▌| 62915/66186 [01:55<00:10, 310.56it/s]

Simple path:  95%|█████████▌| 62947/66186 [01:56<00:10, 307.82it/s]

Simple path:  95%|█████████▌| 62978/66186 [01:56<00:10, 303.28it/s]

Simple path:  95%|█████████▌| 63009/66186 [01:56<00:10, 298.73it/s]

Simple path:  95%|█████████▌| 63039/66186 [01:56<00:10, 296.71it/s]

Simple path:  95%|█████████▌| 63080/66186 [01:56<00:09, 329.65it/s]

Simple path:  95%|█████████▌| 63141/66186 [01:56<00:07, 411.53it/s]

Simple path:  95%|█████████▌| 63203/66186 [01:56<00:06, 471.29it/s]

Simple path:  96%|█████████▌| 63264/66186 [01:56<00:05, 511.55it/s]

Simple path:  96%|█████████▌| 63325/66186 [01:56<00:05, 540.23it/s]

Simple path:  96%|█████████▌| 63386/66186 [01:56<00:04, 560.78it/s]

Simple path:  96%|█████████▌| 63447/66186 [01:57<00:04, 573.76it/s]

Simple path:  96%|█████████▌| 63508/66186 [01:57<00:04, 583.69it/s]

Simple path:  96%|█████████▌| 63569/66186 [01:57<00:04, 591.26it/s]

Simple path:  96%|█████████▌| 63631/66186 [01:57<00:04, 597.09it/s]

Simple path:  96%|█████████▌| 63692/66186 [01:57<00:04, 599.92it/s]

Simple path:  96%|█████████▋| 63753/66186 [01:57<00:04, 599.92it/s]

Simple path:  96%|█████████▋| 63814/66186 [01:57<00:03, 601.50it/s]

Simple path:  97%|█████████▋| 63875/66186 [01:57<00:03, 600.56it/s]

Simple path:  97%|█████████▋| 63936/66186 [01:57<00:03, 600.76it/s]

Simple path:  97%|█████████▋| 63997/66186 [01:57<00:03, 598.23it/s]

Simple path:  97%|█████████▋| 64057/66186 [01:58<00:03, 594.57it/s]

Simple path:  97%|█████████▋| 64117/66186 [01:58<00:03, 593.53it/s]

Simple path:  97%|█████████▋| 64177/66186 [01:58<00:03, 592.02it/s]

Simple path:  97%|█████████▋| 64237/66186 [01:58<00:03, 590.77it/s]

Simple path:  97%|█████████▋| 64297/66186 [01:58<00:03, 590.62it/s]

Simple path:  97%|█████████▋| 64357/66186 [01:58<00:03, 590.69it/s]

Simple path:  97%|█████████▋| 64417/66186 [01:58<00:02, 589.98it/s]

Simple path:  97%|█████████▋| 64477/66186 [01:58<00:02, 591.03it/s]

Simple path:  98%|█████████▊| 64537/66186 [01:58<00:02, 591.89it/s]

Simple path:  98%|█████████▊| 64597/66186 [01:58<00:02, 591.99it/s]

Simple path:  98%|█████████▊| 64657/66186 [01:59<00:02, 534.15it/s]

Simple path:  98%|█████████▊| 64712/66186 [01:59<00:03, 396.06it/s]

Simple path:  98%|█████████▊| 64758/66186 [01:59<00:04, 343.37it/s]

Simple path:  98%|█████████▊| 64798/66186 [01:59<00:04, 314.97it/s]

Simple path:  98%|█████████▊| 64833/66186 [01:59<00:04, 294.77it/s]

Simple path:  98%|█████████▊| 64865/66186 [01:59<00:04, 282.48it/s]

Simple path:  98%|█████████▊| 64895/66186 [02:00<00:04, 276.40it/s]

Simple path:  98%|█████████▊| 64924/66186 [02:00<00:04, 264.21it/s]

Simple path:  98%|█████████▊| 64951/66186 [02:00<00:04, 261.69it/s]

Simple path:  98%|█████████▊| 64978/66186 [02:00<00:04, 254.23it/s]

Simple path:  98%|█████████▊| 65004/66186 [02:00<00:04, 250.88it/s]

Simple path:  98%|█████████▊| 65030/66186 [02:00<00:04, 244.52it/s]

Simple path:  98%|█████████▊| 65056/66186 [02:00<00:04, 244.25it/s]

Simple path:  98%|█████████▊| 65081/66186 [02:00<00:04, 238.20it/s]

Simple path:  98%|█████████▊| 65105/66186 [02:00<00:04, 234.11it/s]

Simple path:  98%|█████████▊| 65130/66186 [02:01<00:04, 237.14it/s]

Simple path:  98%|█████████▊| 65157/66186 [02:01<00:04, 243.81it/s]

Simple path:  98%|█████████▊| 65182/66186 [02:01<00:04, 235.88it/s]

Simple path:  99%|█████████▊| 65208/66186 [02:01<00:04, 241.14it/s]

Simple path:  99%|█████████▊| 65234/66186 [02:01<00:03, 245.05it/s]

Simple path:  99%|█████████▊| 65259/66186 [02:01<00:03, 246.24it/s]

Simple path:  99%|█████████▊| 65284/66186 [02:01<00:03, 226.26it/s]

Simple path:  99%|█████████▊| 65308/66186 [02:01<00:03, 227.27it/s]

Simple path:  99%|█████████▊| 65331/66186 [02:01<00:03, 225.41it/s]

Simple path:  99%|█████████▊| 65358/66186 [02:02<00:03, 236.71it/s]

Simple path:  99%|█████████▉| 65384/66186 [02:02<00:03, 242.10it/s]

Simple path:  99%|█████████▉| 65409/66186 [02:02<00:03, 240.33it/s]

Simple path:  99%|█████████▉| 65434/66186 [02:02<00:03, 230.32it/s]

Simple path:  99%|█████████▉| 65459/66186 [02:02<00:03, 234.07it/s]

Simple path:  99%|█████████▉| 65483/66186 [02:02<00:03, 229.53it/s]

Simple path:  99%|█████████▉| 65507/66186 [02:02<00:03, 219.84it/s]

Simple path:  99%|█████████▉| 65531/66186 [02:02<00:02, 224.75it/s]

Simple path:  99%|█████████▉| 65554/66186 [02:02<00:02, 219.04it/s]

Simple path:  99%|█████████▉| 65577/66186 [02:03<00:02, 219.50it/s]

Simple path:  99%|█████████▉| 65600/66186 [02:03<00:02, 219.82it/s]

Simple path:  99%|█████████▉| 65624/66186 [02:03<00:02, 224.45it/s]

Simple path:  99%|█████████▉| 65647/66186 [02:03<00:02, 220.12it/s]

Simple path:  99%|█████████▉| 65672/66186 [02:03<00:02, 227.70it/s]

Simple path:  99%|█████████▉| 65695/66186 [02:03<00:02, 227.78it/s]

Simple path:  99%|█████████▉| 65718/66186 [02:03<00:02, 225.12it/s]

Simple path:  99%|█████████▉| 65741/66186 [02:03<00:02, 221.72it/s]

Simple path:  99%|█████████▉| 65764/66186 [02:03<00:01, 223.36it/s]

Simple path:  99%|█████████▉| 65787/66186 [02:03<00:01, 219.82it/s]

Simple path:  99%|█████████▉| 65811/66186 [02:04<00:01, 221.80it/s]

Simple path:  99%|█████████▉| 65834/66186 [02:04<00:01, 214.55it/s]

Simple path: 100%|█████████▉| 65856/66186 [02:04<00:01, 215.89it/s]

Simple path: 100%|█████████▉| 65878/66186 [02:04<00:01, 210.64it/s]

Simple path: 100%|█████████▉| 65901/66186 [02:04<00:01, 213.72it/s]

Simple path: 100%|█████████▉| 65925/66186 [02:04<00:01, 219.08it/s]

Simple path: 100%|█████████▉| 65947/66186 [02:04<00:01, 218.77it/s]

Simple path: 100%|█████████▉| 65970/66186 [02:04<00:00, 220.43it/s]

Simple path: 100%|█████████▉| 65993/66186 [02:04<00:00, 214.69it/s]

Simple path: 100%|█████████▉| 66018/66186 [02:05<00:00, 221.98it/s]

Simple path: 100%|█████████▉| 66044/66186 [02:05<00:00, 229.45it/s]

Simple path: 100%|█████████▉| 66067/66186 [02:05<00:00, 228.61it/s]

Simple path: 100%|█████████▉| 66090/66186 [02:05<00:00, 226.22it/s]

Simple path: 100%|█████████▉| 66113/66186 [02:05<00:00, 222.94it/s]

Simple path: 100%|█████████▉| 66136/66186 [02:05<00:00, 222.32it/s]

Simple path: 100%|█████████▉| 66159/66186 [02:05<00:00, 218.15it/s]

Simple path: 100%|██████████| 66186/66186 [02:05<00:00, 526.66it/s]

Simple path: 66,186 cases in 125.7s

=== Power-law routing gate: R² >= 0.90, |b−1| <= 0.05 ===

,Family ID,Family,Total,Linear,Concave,Convex,Enter cubic/S/Threshold branch,Accuracy
0,F01,Linear positive,"11,756","10,290 (87.5%)",154 (1.3%),173 (1.5%),"1,139 (9.7%)","10,290/11,756 (87.5%)"
1,F03,Power convex positive,"10,576",0 (0.0%),0 (0.0%),"10,192 (96.4%)",384 (3.6%),"10,192/10,576 (96.4%)"
2,F05,Power concave positive,"11,057",0 (0.0%),"10,549 (95.4%)",0 (0.0%),508 (4.6%),"10,549/11,057 (95.4%)"
3,F13,S-curve positive,"11,931",1 (0.0%),"1,487 (12.5%)","3,292 (27.6%)","7,151 (59.9%)","7,151/11,931 (59.9%)"
4,F15,Threshold positive,"9,872",0 (0.0%),0 (0.0%),0 (0.0%),"9,872 (100.0%)","9,872/9,872 (100.0%)"
5,F21,Cubic,"3,099",0 (0.0%),845 (27.3%),772 (24.9%),"1,482 (47.8%)","1,482/3,099 (47.8%)"
6,Overall,All six families,"58,291","10,291 (17.7%)","13,035 (22.4%)","14,429 (24.8%)","20,536 (35.2%)","49,536/58,291 (85.0%)"

Routing accuracy: 49,536/58,291 (85.0%)

=== Cubic turning-point gate (only cases entering from the previous gate) ===

,Family ID,Family,Total entering gate,Cubic,Enter S/Threshold gate,Other/Uncertain,Accuracy
0,F01,Linear positive,"1,139",0 (0.0%),"1,139 (100.0%)",0 (0.0%),"0/1,139 (0.0%)"
1,F03,Power convex positive,384,0 (0.0%),384 (100.0%),0 (0.0%),0/384 (0.0%)
2,F05,Power concave positive,508,0 (0.0%),508 (100.0%),0 (0.0%),0/508 (0.0%)
3,F13,S-curve positive,"7,151","2,084 (29.1%)","5,067 (70.9%)",0 (0.0%),"5,067/7,151 (70.9%)"
4,F15,Threshold positive,"9,872","5,100 (51.7%)","4,772 (48.3%)",0 (0.0%),"4,772/9,872 (48.3%)"
5,F21,Cubic,"1,482","1,482 (100.0%)",0 (0.0%),0 (0.0%),"1,482/1,482 (100.0%)"
6,Overall,All cases entering this gate,"20,536","8,666 (42.2%)","11,870 (57.8%)",0 (0.0%),"11,321/20,536 (55.1%)"

Gate accuracy: 11,321/20,536 (55.1%)

## Save results

In [8]:
output_cols = [
    'case_id', '_pt_idx', 'family_id', 'family_name', 'canonical_family',
    'strength_name', 'snr', 'snr_float', 'replicate',
    'MIC', 'pearson_r', 'spearman_rho',
    'gate1', 'gate2', 'shape_label', 'broad_shape', 'shape_details',
]
if 'is_representative' in data.columns:
    output_cols.insert(4, 'is_representative')

result = data[output_cols].copy()
result = result.rename(columns={'_pt_idx': 'scatter_point_index'})
result.to_parquet(OUT_DIR / 'shape_classification.parquet', index=False)
result.to_csv(OUT_DIR / 'shape_classification.csv', index=False)

print(f'Saved {len(result):,} rows to {OUT_DIR.relative_to(REPO_ROOT)}/')
print(f'  shape_classification.parquet')
print(f'  shape_classification.csv')

Saved 335,960 rows to F/output/S3_shape_classification_new_data/
  shape_classification.parquet
  shape_classification.csv

## Summary & validation

Compare predicted shape labels against the known `family_id` ground truth.

In [9]:
# Overall shape label distribution
print('=== Shape label distribution ===')
_shape_counts = data['shape_label'].value_counts()
_shape_distribution = pd.DataFrame({
    'shape_label': _shape_counts.index,
    'Count (share)': [count_percent(n, len(data)) for n in _shape_counts],
})
print(_shape_distribution.to_string(index=False))
print()

# Evaluate the current Simple-path label resolution rather than comparing it
# with finer Complex labels that this notebook does not attempt to predict.
EXPECTED_BROAD_SHAPE = {
    'F01': 'line', 'F02': 'line',
    'F03': 'convex', 'F04': 'concave',
    'F05': 'concave', 'F06': 'convex',
    'F07': 'concave', 'F08': 'convex',
    'F09': 'concave', 'F10': 'convex',
    'F11': 'convex', 'F12': 'concave',
    'F13': 'S/threshold', 'F14': 'S/threshold',
    'F15': 'S/threshold', 'F16': 'S/threshold',
    'F21': 'cubic',
}

high_snr = data[pd.to_numeric(data['snr_float'], errors='coerce') >= 10].copy()
high_snr['expected_broad_shape'] = high_snr['family_id'].map(EXPECTED_BROAD_SHAPE)
eligible_high = high_snr[high_snr['expected_broad_shape'].notna()].copy()
eligible_high['entered_simple'] = eligible_high['gate2'].eq('Simple')
shape_eval = eligible_high[eligible_high['entered_simple']].copy()
shape_eval['predicted_broad_shape'] = shape_eval['broad_shape'].fillna('other')
shape_eval['correct'] = (
    shape_eval['predicted_broad_shape'] == shape_eval['expected_broad_shape']
)

coverage = eligible_high.groupby('family_id', as_index=False).agg(
    family_name=('family_name', 'first'),
    expected_broad_shape=('expected_broad_shape', 'first'),
    high_snr_input=('case_id', 'size'),
    entered_simple=('entered_simple', 'sum'),
)
coverage['simple_path_coverage'] = coverage['entered_simple'] / coverage['high_snr_input']
shape_accuracy = shape_eval.groupby('family_id', as_index=False).agg(
    correctly_classified=('correct', 'sum'),
    top_predicted=('predicted_broad_shape', lambda s: s.value_counts().index[0]),
)
accuracy = coverage.merge(shape_accuracy, on='family_id', how='left')
accuracy['correctly_classified'] = accuracy['correctly_classified'].fillna(0).astype(int)
accuracy['conditional_accuracy'] = np.divide(
    accuracy['correctly_classified'], accuracy['entered_simple'],
    out=np.full(len(accuracy), np.nan), where=accuracy['entered_simple'].to_numpy() > 0,
)

print('=== High-SNR Simple-path coverage and broad-shape accuracy ===')
accuracy_display = accuracy[[
    'family_id', 'family_name', 'expected_broad_shape', 'high_snr_input',
    'entered_simple', 'correctly_classified', 'top_predicted',
]].copy()
accuracy_display['High-SNR input'] = [count_percent(n, n) for n in accuracy['high_snr_input']]
accuracy_display['Entered Simple'] = [
    count_percent(n, total) for n, total in zip(accuracy['entered_simple'], accuracy['high_snr_input'])
]
accuracy_display['Correct'] = [
    count_percent(n, total) for n, total in zip(accuracy['correctly_classified'], accuracy['entered_simple'])
]
accuracy_display = accuracy_display[[
    'family_id', 'family_name', 'expected_broad_shape', 'High-SNR input',
    'Entered Simple', 'top_predicted', 'Correct',
]]
print(accuracy_display.to_string(index=False))
overall_coverage = len(shape_eval) / len(eligible_high) if len(eligible_high) else np.nan
overall_accuracy = shape_eval['correct'].mean() if len(shape_eval) else np.nan
print(f'\nSimple-path coverage: {len(shape_eval):,}/{len(eligible_high):,} ({overall_coverage:.1%})')
print(f'Conditional broad-shape accuracy: {shape_eval["correct"].sum():,}/{len(shape_eval):,} ({overall_accuracy:.1%})')
print('Complex families are excluded here because this notebook currently reports only the broad label Complex.')
accuracy.to_csv(OUT_DIR / 'simple_path_broad_accuracy_high_snr.csv', index=False)

=== Shape label distribution ===
            shape_label   Count (share)
              no_global 210,792 (62.7%)
    intermediate_global   32,706 (9.7%)
                complex   26,276 (7.8%)
        positive_convex   16,738 (5.0%)
       positive_concave   13,601 (4.0%)
   positive_s_threshold   11,915 (3.5%)
          positive_line   10,291 (3.1%)
cubic_two_turning_point    9,433 (2.8%)
   negative_s_threshold    3,219 (1.0%)
       negative_concave      845 (0.3%)
        negative_convex      144 (0.0%)

=== High-SNR Simple-path coverage and broad-shape accuracy ===
family_id            family_name expected_broad_shape  High-SNR input  Entered Simple top_predicted         Correct
      F01        Linear positive                 line 10,440 (100.0%) 10,440 (100.0%)          line  10,150 (97.2%)
      F03  Power convex positive               convex 10,440 (100.0%)  10,094 (96.7%)        convex 10,089 (100.0%)
      F05 Power concave positive              concave 10,440 (100.0%)  10,404 (99.7%)       concave  10,395 (99.9%)
      F07    Saturation positive              concave 10,440 (100.0%)   2,178 (20.9%)       concave   1,411 (64.8%)
      F13       S-curve positive          S/threshold 10,440 (100.0%) 10,440 (100.0%)   S/threshold   3,989 (38.2%)
      F15     Threshold positive          S/threshold 10,440 (100.0%)   8,264 (79.2%)         cubic   4,117 (49.8%)
      F21                  Cubic                cubic 10,440 (100.0%)   3,099 (29.7%)         cubic   1,482 (47.8%)

Simple-path coverage: 54,919/73,080 (75.1%)
Conditional broad-shape accuracy: 41,633/54,919 (75.8%)
Complex families are excluded here because this notebook currently reports only the broad label Complex.

In [10]:
# Cross-tabulation: family × shape_label for high SNR
print('=== Family × Shape Label (SNR >= 10, strong_global only) ===')
ct_counts = high_snr[high_snr['gate1'] == 'strong_global'].groupby(
    ['family_id', 'shape_label']
).size().unstack(fill_value=0)
ct_totals = ct_counts.sum(axis=1)
ct = pd.DataFrame(index=ct_counts.index)
ct['family_name'] = ct.index.map(lambda f: FAMILY_CATALOGUE.get(f, {}).get('name', ''))
ct['Total'] = [count_percent(n, n) for n in ct_totals]
for col in ct_counts.columns:
    ct[col] = [count_percent(n, total) for n, total in zip(ct_counts[col], ct_totals)]
display(ct)

=== Family × Shape Label (SNR >= 10, strong_global only) ===

,family_name,Total,complex,cubic_two_turning_point,negative_concave,negative_convex,negative_s_threshold,positive_concave,positive_convex,positive_line,positive_s_threshold
family_id,,,,,,,,,,,
F01,Linear positive,"10,440 (100.0%)",0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),134 (1.3%),151 (1.4%),"10,150 (97.2%)",5 (0.0%)
F03,Power convex positive,"10,094 (100.0%)",0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),"10,089 (100.0%)",0 (0.0%),5 (0.0%)
F05,Power concave positive,"10,404 (100.0%)",0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),"10,395 (99.9%)",0 (0.0%),0 (0.0%),9 (0.1%)
F07,Saturation positive,"2,936 (100.0%)",758 (25.8%),767 (26.1%),0 (0.0%),0 (0.0%),0 (0.0%),"1,411 (48.1%)",0 (0.0%),0 (0.0%),0 (0.0%)
F13,S-curve positive,"10,440 (100.0%)",0 (0.0%),"1,671 (16.0%)",0 (0.0%),0 (0.0%),0 (0.0%),"1,487 (14.2%)","3,292 (31.5%)",1 (0.0%),"3,989 (38.2%)"
F15,Threshold positive,"10,436 (100.0%)","2,172 (20.8%)","4,147 (39.7%)",0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),"4,117 (39.4%)"
F18,Quadratic valley (U),"9,992 (100.0%)","4,318 (43.2%)",0 (0.0%),0 (0.0%),107 (1.1%),"3,212 (32.1%)",0 (0.0%),"2,345 (23.5%)",0 (0.0%),10 (0.1%)
F21,Cubic,"6,578 (100.0%)","3,479 (52.9%)","1,482 (22.5%)",845 (12.8%),37 (0.6%),0 (0.0%),0 (0.0%),735 (11.2%),0 (0.0%),0 (0.0%)
F22,Oscillation,"10,440 (100.0%)","10,440 (100.0%)",0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
F23,Two Lines,"2,412 (100.0%)","2,385 (98.9%)",0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),27 (1.1%)
F25,Multi-regime threshold,190 (100.0%),190 (100.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)
F26,Windowed threshold,171 (100.0%),171 (100.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%),0 (0.0%)